// @generated by scripts/build.mjs — do not edit by hand.
window.__ModuleLoader__.load({
  id: 'dsh-opencode-free-models',
  factory: function (require, module) {
'use strict'
// dsh-opencode-free-models · pure core helpers (source of truth).
//
// Side-effect free so it can be unit-tested directly under node:test. The
// client bundle (lib/client.cjs) is generated by scripts/build.mjs, which
// concatenates THIS file (exports stripped) with src/client/index.js inside a
// lazy-CJS factory. Keep this file free of browser globals.
//
// Adapted from the dsh-free-models-hub reference plugin (MIT) for OpenCode Zen
// free models, which authenticate with one shared literal key ("public")
// injected by the host — so there is no per-user key and no rotation proxy.

const PLUGIN_ID = 'opencode-free-models'
const LOG_PREFIX = '[opencode-free-models]'
const SETTINGS_NS = 'llm-pi-ai'
const SECTION_NS = 'opencode-free-models'

// All OpenCode Zen free providers share this single literal-key env var. The
// host half injects OPENCODE_ZEN_API_KEY="public" on load, so no user key is
// ever required or touched by this plugin.
const PUBLIC_KEY_ENV = 'OPENCODE_ZEN_API_KEY'

const DEFAULT_FOOTER_LINKS = Object.freeze([
  Object.freeze({ label: '技术笔记', url: 'http://blog.4wc.cn' }),
  Object.freeze({ label: '插件开发', url: 'https://blog.gd7.cn/' }),
  Object.freeze({ label: '联系站长', url: 'http://web.wuyiyun.cn/' }),
])

const CONFIG_DEFAULTS = Object.freeze({
  backendUrl: 'https://free-api.gd7.cn/opencode',
  pageSize: 20,
  requestTimeoutMs: 10000,
  uiSlot: '', // empty = deterministic right-edge drawer with its own toggle
  providerIdPrefix: 'opencode',
  footerLinks: DEFAULT_FOOTER_LINKS,
  debug: false,
})

/** Coerce to an integer inside [min,max]; anything else falls back. */
function clampInt(value, min, max, fallback) {
  const n = Math.floor(Number(value))
  if (!Number.isFinite(n)) return fallback
  return Math.min(max, Math.max(min, n))
}

/** Only http(s) absolute URLs count as safe targets for links or fetches.
 *  Returns the canonical serialized URL — what we validate is exactly what
 *  the caller will use (the WHATWG parser strips smuggled control chars). */
function safeHttpUrl(value) {
  if (typeof value !== 'string') return ''
  const trimmed = value.trim()
  if (!trimmed || trimmed.length > 2048) return ''
  let parsed
  try {
    parsed = new URL(trimmed)
  } catch {
    return ''
  }
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') return ''
  return parsed.toString()
}

/** Stable, lowercase provider-id fragment derived from a model title. */
function slugify(title, maxLen = 40) {
  const base = String(title ?? '')
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, maxLen)
    .replace(/-+$/g, '')
  return base || 'model'
}

function providerId(prefix, title, rowId) {
  const safePrefix = typeof prefix === 'string' && /^[a-z][a-z0-9-]{0,20}$/.test(prefix) ? prefix : 'opencode'
  const slug = slugify(title)
  if (Number.isFinite(rowId) && rowId > 0) return `${safePrefix}-${slug}-${rowId}`
  return `${safePrefix}-${slug}`
}

/** Single shared literal-key env for every OpenCode Zen free provider. */
function apiKeyEnvName(/* pid */) {
  return PUBLIC_KEY_ENV
}

/**
 * Normalize raw patch/user config into a safe, fully-defaulted object.
 * Returns { value, warnings: string[] }; invalid fields fall back loudly.
 */
function normalizeConfig(raw) {
  const src = raw && typeof raw === 'object' ? raw : {}
  const warnings = []
  const out = {}

  const backendUrl = safeHttpUrl(src.backendUrl)
  if (backendUrl) {
    out.backendUrl = backendUrl.replace(/\/+$/, '')
  } else {
    if (typeof src.backendUrl === 'string' && src.backendUrl.trim() !== '') {
      warnings.push(`backendUrl ignored (must be an absolute http/https URL): ${String(src.backendUrl).slice(0, 120)}`)
    }
    out.backendUrl = ''
  }

  out.pageSize = clampInt(src.pageSize, 1, 50, CONFIG_DEFAULTS.pageSize)
  out.requestTimeoutMs = clampInt(src.requestTimeoutMs, 1000, 60000, CONFIG_DEFAULTS.requestTimeoutMs)

  if (typeof src.uiSlot === 'string' && src.uiSlot.trim().length <= 64) {
    out.uiSlot = src.uiSlot.trim()
  } else {
    out.uiSlot = CONFIG_DEFAULTS.uiSlot
    if (src.uiSlot != null) warnings.push('uiSlot reset to default (non-empty string <= 64 chars expected)')
  }

  if (typeof src.providerIdPrefix === 'string' && /^[a-z][a-z0-9-]{0,20}$/.test(src.providerIdPrefix)) {
    out.providerIdPrefix = src.providerIdPrefix
  } else {
    out.providerIdPrefix = CONFIG_DEFAULTS.providerIdPrefix
    if (src.providerIdPrefix != null) warnings.push('providerIdPrefix reset to "opencode" (lowercase letters/digits/dashes, starts with a letter)')
  }

  const links = []
  if (Array.isArray(src.footerLinks)) {
    for (const raw of src.footerLinks.slice(0, 6)) {
      const item = raw && typeof raw === 'object' ? raw : {}
      const label = typeof item.label === 'string' ? item.label.trim().slice(0, 24) : ''
      const url = safeHttpUrl(item.url)
      if (label && url) links.push({ label, url })
      else warnings.push(`footerLink dropped (need label + http/https url): ${JSON.stringify(item).slice(0, 80)}`)
    }
  }
  out.footerLinks = links.length > 0 ? links : [...DEFAULT_FOOTER_LINKS]

  out.debug = src.debug === true

  return { value: out, warnings }
}

/**
 * Pagination window: numbers and '…' markers.
 */
function pageWindow(current, total, width = 7) {
  const tot = clampInt(total, 1, Number.MAX_SAFE_INTEGER, 1)
  const cur = Math.min(clampInt(current, 1, Number.MAX_SAFE_INTEGER, 1), tot)
  const w = Math.max(5, clampInt(width, 5, 15, 7))
  if (tot <= w) {
    const all = []
    for (let i = 1; i <= tot; i++) all.push(i)
    return all
  }
  const mid = w - 2
  let start = Math.max(2, cur - ((mid - 1) >> 1))
  let end = Math.min(tot - 1, start + mid - 1)
  if (end >= tot - 1) {
    end = tot - 1
    start = Math.max(2, end - mid + 1)
  }
  const pages = [1]
  if (start > 2) pages.push('…')
  for (let i = start; i <= end; i++) pages.push(i)
  if (end < tot - 1) pages.push('…')
  pages.push(tot)
  return pages
}

function yamlQuote(value) {
  return `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

/** Fallback YAML snippet shown when live settings writes are unavailable. */
function toYamlSnippet({ pid, entry }) {
  const lines = [
    'llm-pi-ai:',
    '  providers:',
    `    ${pid}:`,
    `      api: ${entry.api}`,
    `      baseURL: ${yamlQuote(entry.baseURL)}`,
    '      compat:',
    `        supportsDeveloperRole: ${entry.compat.supportsDeveloperRole}`,
    `        maxTokensField: ${entry.compat.maxTokensField}`,
    '      models:',
  ]
  for (const m of entry.models) {
    lines.push(`        - id: ${yamlQuote(m.id)}`)
  }
  return lines.join('\n')
}

/**
 * Build one llm-pi-ai provider entry for an OpenCode Zen free model.
 *
 * OpenCode Zen free models are PUBLIC: the completion API returns 200 with no
 * Authorization header at all (and equivalently accepts `Bearer public`). So
 * the entry deliberately declares NO apiKeyEnv — if we declared one, pi-ai
 * would demand that credential from its credentials service and report
 * "no credential". Omitting apiKeyEnv lets pi-ai use its own environment
 * discovery, which performs a no-auth request that the public API accepts.
 */
function buildProviderEntry({ prefix, title, apiBase, modelIds, rowId }) {
  const pid = providerId(prefix, title, rowId)
  const models = Array.isArray(modelIds) && modelIds.length > 0
    ? modelIds.filter((m) => typeof m === 'string' && m.trim() !== '').map((m) => ({ id: m.trim() }))
    : [{ id: String(modelIds || '') }]
  return {
    pid,
    entry: {
      api: 'openai-completions',
      baseURL: String(apiBase),
      compat: {
        supportsDeveloperRole: false,
        maxTokensField: 'max_tokens',
      },
      models,
    },
  }
}

/**
 * Validate + map the OpenCode Zen free-models payload into canonical items.
 * Drops malformed rows instead of throwing on single bad entries.
  * Canonical item: { id, title, apiBase, modelIds, keyUrl, badge, pinned, status, disabledReason, free }
 */
function parseModelsResponse(payload, pageSize) {
  if (!payload || typeof payload !== 'object' || payload.ok !== true) {
    throw new TypeError('response is not a valid models payload')
  }
  const total = clampInt(payload.total, 0, Number.MAX_SAFE_INTEGER, 0)
  const totalPages = clampInt(payload.total_pages, 1, Number.MAX_SAFE_INTEGER, 1)
  const page = clampInt(payload.page, 1, totalPages, 1)
  const size = clampInt(payload.page_size, 1, 50, clampInt(pageSize, 1, 50, 10))
  const rawItems = Array.isArray(payload.items) ? payload.items : []
  const items = []
  for (const row of rawItems.slice(0, size)) {
    if (!row || typeof row !== 'object') continue
    const id = Number(row.id)
    const title = typeof row.title === 'string' ? row.title.trim().slice(0, 200) : ''
    const apiBase = safeHttpUrl(row.api_base_url)
    let modelIds = []
    if (Array.isArray(row.model_name)) {
      modelIds = row.model_name.filter((m) => typeof m === 'string' && m.trim() !== '').map((m) => m.trim().slice(0, 120))
    } else if (typeof row.model_name === 'string' && row.model_name.trim() !== '') {
      modelIds = [row.model_name.trim().slice(0, 120)]
    }
    const keyUrl = safeHttpUrl(row.key_apply_url)
    const badge = (row.badge === 'hot' || row.badge === 'rec' || row.badge === 'free' || row.badge === 'paid') ? row.badge : ''
    const pinned = row.pinned === 1 || row.pinned === true
    const status = row.status === 'disabled' ? 'disabled' : 'enabled'
    const disabledReason = typeof row.disabled_reason === 'string' ? row.disabled_reason.slice(0, 120) : ''
    const usable = row.usable === false ? false : true
    const free = row.free === 1 || row.free === true
    const availableFrom = typeof row.available_from === 'string' ? row.available_from.slice(0, 32) : ''
    const availableUntil = typeof row.available_until === 'string' ? row.available_until.slice(0, 32) : ''
    if (!Number.isFinite(id) || !title || !apiBase || modelIds.length === 0) continue
    items.push({ id, title, apiBase, modelIds, keyUrl, badge, pinned, status, disabledReason, usable, availableFrom, availableUntil, free })
  }
  const globalEnabled = payload.opencode_enabled === false ? false : true
  return { total, totalPages, page, pageSize: size, items, globalEnabled }
}

/* global safeHttpUrl slugify providerId buildProviderEntry toYamlSnippet clampInt parseModelsResponse pageWindow apiKeyEnvName */

const name = 'opencode-free-models-client'

const inject = ['slots', 'settingsScope']

const STR = Object.freeze({
  panelTitle: 'OpenCode Zen 免费模型',
  close: '关闭',
  setupTitle: '配置数据源',
  setupHint: '填入 OpenCode Zen 后端地址（域名根，例如 https://your-domain.com/opencode）',
  setupPlaceholder: 'https://your-domain.com/opencode',
  setupSave: '保存数据源',
  loading: '加载中…',
  retry: '重试',
  empty: '站长还没有发布免费模型',
  errNet: '无法连接数据源，请稍后重试。',
  errCors: '若持续失败，请站长在后台「系统设置 → CORS 白名单」中加入本页地址。',
  apiLabel: 'API 调用地址',
  modelLabel: '模型名称',
  applyBtn: '一键置入',
  applied: (pid) => `已置入 ${pid} —— 到 设置 → 模型 即可选用（无需密钥）`,
  removeBtn: '取消置入',
  removed: (pid) => `已取消置入 ${pid} —— 模型已从 DSH 模型选择器移除`,
  paused: '插件已暂停（后台已关闭，模型仅可见、暂不可用）',
  notStarted: '未开始',
  expired: '已过期',
  windowLabel: (from, until) => `可用时间：${from || '—'} ~ ${until || '—'}`,
  launcherTitle: '免费模型 · 无需登录，无需密钥key即用',
  applying: '正在写入配置…',
  copied: '已复制',
  copyFail: '复制失败，请手动选择文本',
  pageInfo: (total, cur, tot) => `共 ${total} 个 · 第 ${cur}/${tot} 页`,
  first: '首页',
  prev: '上一页',
  next: '下一页',
  last: '末页',
  fallbackTitle: '一键配置需要手动收尾',
  fallbackBody: '当前版本未能自动写入设置。请将下面 YAML 加入 $DSH_HOME/settings.yaml（或在 设置 → 模型 手动添加自定义提供方）：',
  fallbackCopy: '复制 YAML',
  fallbackClose: '我知道了',
  badSource: '数据源地址无效（需 http/https 绝对地址）',
  batchBtn: '⚡ 配置本页全部',
  batchApplying: (n) => `正在配置 ${n} 个模型…`,
  batchDone: (ok, fail) => `批量配置完成：成功 ${ok} 个${fail ? `，失败 ${fail} 个` : ''}`,
  badgeHot: '热门',
  badgeRec: '推荐',
  refreshBtn: '🔄 刷新',
  refreshing: '刷新中…',
  upgradeBtn: '⬆ 升级',
  upgradeChecking: '检查更新…',
  upgradeLatest: '已是最新版本',
  upgradeNew: (v) => `发现新版本 v${v}`,
  upgradeFailed: '检查更新失败',
  noKey: '无需密钥，一键即可用',
  disabled: '已下架',
  badgeFree: '免费',
  badgePaid: '收费',
  freeModel: '该模型为免费模型，无需密钥、无需一键置入（按钮已禁用）。',
  applyKeyBtn: '🔑 点击这里申请免费密钥key',
  // 文章 / 公告
  articlesTitle: '📰 文章 / 公告',
  articlesEmpty: '暂无文章',
  announcementHint: '📣 公告',
  articleOpen: '查看文章内容',
  maximize: '最大化',
  minimize: '收起',
  restore: '还原',
  articleLoading: '加载文章内容…',
  articleErr: '文章加载失败',
  articleClose: '关闭',
  launcherShort: '🎁 免费模型',
  tabContent: '内容',
  tabLink: '链接 / 浏览',
  openNew: '在新窗口打开',
  authTitle: '插件授权验证',
  authHint: '本插件需要授权码方可使用。请填写您的信息并输入授权码提交。',
  authName: '姓名',
  authPhone: '手机号',
  authWechat: '微信号',
  authEmail: '邮箱',
  authCode: '授权码',
  authSubmit: '提交并激活',
  authVerifying: '验证中…',
  authErrRequired: '请完整填写姓名、手机号、微信号、邮箱与授权码。',
  authErrInvalid: '授权码无效、已过期或已被使用，请核对后重试。',
  authErrNet: '网络异常，请稍后重试。',
})

const DEFAULTS = Object.freeze({
  backendUrl: 'https://free-api.gd7.cn/opencode',
  pageSize: 20,
  requestTimeoutMs: 10000,
  uiSlot: '',
  providerIdPrefix: 'opencode',
  footerLinks: [
    { label: '技术笔记', url: 'http://blog.4wc.cn' },
    { label: '插件开发', url: 'https://blog.gd7.cn/' },
    { label: '联系站长', url: 'http://web.wuyiyun.cn/' },
  ],
})

const LS_BACKEND = 'ozf:backendUrl'
const LS_OPEN = 'ozf:drawerOpen'

/* ------------------------------------------------------------------ utils */
function dbg(...args) {
  try { console.log('[opencode-free-models]', ...args) } catch { /* ignore */ }
}

/** Minimal XSS-safe element builder: strings become text nodes, never HTML. */
function el(tag, props = {}, children = []) {
  const node = document.createElement(tag)
  for (const [k, v] of Object.entries(props)) {
    if (v == null || v === false) continue
    if (k === 'class') node.className = v
    else if (k === 'text') node.textContent = String(v)
    else if (k.startsWith('on') && typeof v === 'function') node.addEventListener(k.slice(2), v)
    else if (k === 'dataset') Object.assign(node.dataset, v)
    else node.setAttribute(k, v === true ? '' : String(v))
  }
  for (const child of children.flat(Infinity)) {
    if (child == null || child === false) continue
    node.appendChild(typeof child === 'string' ? document.createTextNode(child) : child)
  }
  return node
}

function sanitizeHtml(html) {
  if (typeof html !== 'string') return ''
  let s = String(html)
    .replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi, '')
    .replace(/<script\b[^>]*\/?>/gi, '')
    .replace(/<iframe\b[^>]*\/?>/gi, '')
    .replace(/<\/iframe>/gi, '')
    .replace(/<object\b[^>]*>[\s\S]*?<\/object>/gi, '')
    .replace(/<embed\b[^>]*\/?>/gi, '')
    .replace(/<link\b[^>]*\/?>/gi, '')
    .replace(/<meta\b[^>]*\/?>/gi, '')
    .replace(/\son\w+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi, '')
    .replace(/\shref\s*=\s*(['"])\s*javascript:[^'"]*\1/gi, ' href="#"')
    .replace(/\ssrc\s*=\s*(['"])\s*javascript:[^'"]*\1/gi, '')
  return s
}
function sanitizeEl(raw) {
  const holder = el('div')
  try { holder.innerHTML = sanitizeHtml(raw) } catch { holder.textContent = String(raw || '') }
  return holder
}
function linkKind(url) {
  const u = safeHttpUrl(url)
  if (!u) return ''
  let host = ''
  try { host = new URL(u).pathname.toLowerCase() } catch { return 'page' }
  if (/\.(png|jpe?g|gif|webp|avif|bmp|svg)(\?|#|$)/i.test(host)) return 'image'
  if (/\.(mp4|webm|ogg|ogv|mov|m4v)(\?|#|$)/i.test(host)) return 'video'
  return 'page'
}

function joinApiUrl(base) {
  const clean = base.trim().replace(/\/+$/, '')
  try {
    const u = new URL(clean)
    const p = u.pathname.replace(/\/+$/, '')
    if (/\/api\/models(\.php)?$/i.test(p) || /\.php$/i.test(p)) return u.toString()
    u.pathname = `${p}/api/models`
    return u.toString()
  } catch {
    return ''
  }
}

function apiCandidates(base) {
  const primary = joinApiUrl(base)
  const out = [primary]
  try {
    const alt = new URL(primary)
    alt.pathname = alt.pathname.replace(/\/api\/models$/i, '/api/models.php')
    const s = alt.toString()
    if (s !== primary) out.push(s)
  } catch { /* primary already invalid; single candidate keeps error path */ }
  return out
}

async function copyText(text) {
  try {
    if (navigator.clipboard && typeof navigator.clipboard.writeText === 'function') {
      await navigator.clipboard.writeText(text)
      return true
    }
  } catch { /* fall through */ }
  try {
    const ta = el('textarea', { style: 'position:fixed;opacity:0' })
    ta.value = text
    document.body.appendChild(ta)
    ta.select()
    const ok = document.execCommand('copy')
    ta.remove()
    return ok
  } catch {
    return false
  }
}

function readLocalOverride() {
  try { return localStorage.getItem(LS_BACKEND) || '' } catch { return '' }
}
function saveLocalOverride(url) {
  try { localStorage.setItem(LS_BACKEND, url) } catch { /* ignore */ }
}

function resolveClientConfig(ctx) {
  const cfg = {
    backendUrl: DEFAULTS.backendUrl,
    pageSize: DEFAULTS.pageSize,
    requestTimeoutMs: DEFAULTS.requestTimeoutMs,
    uiSlot: DEFAULTS.uiSlot,
    providerIdPrefix: DEFAULTS.providerIdPrefix,
    footerLinks: [...DEFAULTS.footerLinks],
  }
  try {
    const scope = ctx && ctx.settingsScope
    if (scope && typeof scope.bind === 'function') {
      const bound = scope.bind({ namespace: 'opencode-free-models' })
      const resolved = bound && (bound.value || bound.base || bound)
      if (resolved && typeof resolved === 'object') {
        if (typeof resolved.backendUrl === 'string') cfg.backendUrl = resolved.backendUrl.trim()
        const ps = Number(resolved.pageSize); if (Number.isFinite(ps)) cfg.pageSize = clampInt(ps, 1, 50, cfg.pageSize)
        const tmo = Number(resolved.requestTimeoutMs); if (Number.isFinite(tmo)) cfg.requestTimeoutMs = clampInt(tmo, 1000, 60000, cfg.requestTimeoutMs)
        if (typeof resolved.uiSlot === 'string' && resolved.uiSlot.trim()) cfg.uiSlot = resolved.uiSlot.trim()
        if (typeof resolved.providerIdPrefix === 'string' && /^[a-z][a-z0-9-]{0,20}$/.test(resolved.providerIdPrefix)) cfg.providerIdPrefix = resolved.providerIdPrefix
      if (Array.isArray(resolved.footerLinks)) {
        const links = []
        for (const item of resolved.footerLinks.slice(0, 6)) {
          const label = item && typeof item.label === 'string' ? item.label.trim().slice(0, 24) : ''
          const url = safeHttpUrl(item && item.url)
          if (label && url) links.push({ label, url })
        }
        if (links.length) cfg.footerLinks = links
      }
      }
    }
  } catch (error) {
    dbg('settingsScope probe failed, using defaults:', error && error.message)
  }
  const local = safeHttpUrl(readLocalOverride())
  if (local) cfg.backendUrl = local.replace(/\/+$/, '')
  return cfg
}

/* ------------------------------------------------------------------ style */
const CSS = `
.ozf-toast-wrap{position:fixed;left:50%;bottom:26px;transform:translateX(-50%);z-index:100001;display:flex;flex-direction:column;gap:8px;align-items:center}
.ozf-toast{background:#262a33;color:#eef1f7;border-radius:8px;padding:9px 16px;font-size:12.5px;box-shadow:0 6px 24px rgba(0,0,0,.4);max-width:76vw}
.ozf-toast.ok{border-left:3px solid #34c77b}
.ozf-toast.err{border-left:3px solid #ff6b6b}
.ozf-launcher{position:fixed;right:14px;top:calc(50% + 64px);transform:translateY(-50%);border:none;background:linear-gradient(135deg,#0b8043,#1e9e5a);color:#fff;font-size:13px;font-weight:600;cursor:pointer;z-index:99997;box-shadow:0 4px 16px rgba(0,0,0,.35);display:flex;align-items:center;gap:4px;padding:0 14px;height:46px;border-radius:23px;white-space:nowrap;transition:transform .15s}
.ozf-launcher:hover{transform:translateY(-50%) scale(1.04)}
.ozf-drawer{position:fixed;top:0;right:0;bottom:0;width:min(360px,94vw);z-index:99999;background:#1b1d23;border-left:1px solid #ffffff22;box-shadow:-12px 0 40px rgba(0,0,0,.45);transform:translateX(105%);transition:transform .22s ease;display:flex;flex-direction:column;overflow:hidden}
.ozf-drawer.open{transform:translateX(0)}
.ozf-drawer-head{display:flex;align-items:center;justify-content:space-between;padding:12px 14px;border-bottom:1px solid #ffffff14;color:#e8eaf0;font-weight:600;font-size:13px;flex:0 0 auto}
.ozf-drawer-close{background:none;border:none;color:inherit;font-size:15px;cursor:pointer;opacity:.7;padding:4px 9px;border-radius:6px}
.ozf-drawer-close:hover{opacity:1;background:rgba(255,255,255,.08)}
.ozf-drawer-body{flex:1;overflow:auto;padding:10px 12px;color:#e8eaf0;font:12px/1.5 system-ui,sans-serif}
.ozf-setup{display:flex;flex-direction:column;gap:6px;background:rgba(127,127,127,.08);border-radius:8px;padding:8px;margin-bottom:8px}
.ozf-setup p{margin:0;opacity:.7;font-size:11px}
.ozf-setup input{width:100%;border-radius:6px;border:1px solid #555a;background:transparent;color:inherit;padding:5px 8px;font-size:12px}
.ozf-setup button,.ozf-retry{align-self:flex-start;border:none;border-radius:6px;padding:5px 12px;font-size:12px;cursor:pointer;background:#0b8043;color:#fff}
.ozf-state{padding:10px 4px;text-align:center;opacity:.65;font-size:12px}
.ozf-list{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:2px}
.ozf-row{border-radius:8px}
.ozf-row:hover{background:rgba(127,127,127,.09)}
.ozf-row-title{display:flex;width:100%;gap:6px;align-items:baseline;text-align:left;background:none;border:none;color:inherit;font:inherit;cursor:pointer;padding:5px 6px;border-radius:8px}
.ozf-rank{flex:0 0 auto;min-width:18px;text-align:right;opacity:.55;font-variant-numeric:tabular-nums}
.ozf-name{flex:1 1 auto;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.ozf-caret{flex:0 0 auto;opacity:.45;transition:transform .15s}
.ozf-row-title[aria-expanded="true"] .ozf-caret{transform:rotate(90deg)}
.ozf-detail{display:none;flex-direction:column;gap:6px;margin:2px 6px 8px 30px;padding:8px;border-radius:8px;background:rgba(127,127,127,.1)}
.ozf-detail.open{display:flex}
.ozf-field{display:flex;flex-direction:column;gap:2px}
.ozf-field b{font-weight:600;opacity:.6;font-size:11px}
.ozf-code{display:flex;align-items:center;gap:6px;min-width:0}
.ozf-code code{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font:11px/1.4 ui-monospace,Menlo,Consolas,monospace;background:rgba(0,0,0,.25);padding:3px 6px;border-radius:5px}
.ozf-copy{background:none;border:none;color:inherit;opacity:.6;cursor:pointer;font-size:11px;padding:2px 4px}
.ozf-copy:hover{opacity:1}
.ozf-actions{display:flex;flex-direction:column;gap:6px;margin-top:2px}
.ozf-btn{display:block;text-align:center;border-radius:8px;padding:7px 10px;font-size:12px;cursor:pointer;text-decoration:none;border:1px solid transparent}
button.ozf-btn-apply{background:#0b8043;color:#fff;border:none}
button.ozf-btn-apply[disabled]{opacity:.55;cursor:wait}
.ozf-note{font-size:11px;opacity:.7;background:rgba(11,128,67,.12);border:1px solid #0b804355;border-radius:6px;padding:4px 6px}
.ozf-badge{display:inline-block;font-size:10px;line-height:1;padding:2px 6px;border-radius:999px;margin-left:5px;vertical-align:1px;font-weight:600}
.ozf-badge.hot{background:rgba(212,56,13,.18);color:#ff7875;border:1px solid #a83a35}
.ozf-badge.rec{background:rgba(22,119,255,.16);color:#69b1ff;border:1px solid #1d4ed8}
.ozf-badge.off{background:rgba(120,120,120,.18);color:#bbb;border:1px solid #666}
.ozf-badge.free{background:rgba(82,196,26,.16);color:#73d13d;border:1px solid #389e0d}
.ozf-badge.paid{background:rgba(250,173,20,.16);color:#ffc53d;border:1px solid #d48806}
.ozf-btn-key{background:rgba(82,196,26,.16);color:#73d13d;border:1px solid #389e0d}
a.ozf-btn-key,a.ozf-btn-key:link,a.ozf-btn-key:visited,a.ozf-btn-key:hover,a.ozf-btn-key:active{color:#73d13d;text-decoration:none}
.ozf-banner{display:none;margin:0 0 8px;padding:8px 10px;border-radius:8px;font-size:12px;background:rgba(255,179,0,.14);border:1px solid #ffb30055;color:#ffd479}
.ozf-btn-remove{background:#d9534f;color:#fff;border:none}
.ozf-note.warn{background:rgba(255,179,0,.12);border-color:#ffb30055;color:#ffd479}
.ozf-window{font-size:11px;opacity:.7}
.ozf-pager{display:flex;flex-wrap:wrap;align-items:center;gap:3px;padding:4px 2px 2px}
.ozf-pager button{min-width:24px;height:22px;padding:0 6px;border-radius:6px;border:1px solid #555a;background:none;color:inherit;font-size:11px;cursor:pointer}
.ozf-pager button[aria-current="true"]{background:#0b8043;border-color:#0b8043;color:#fff}
.ozf-pager button:disabled{opacity:.35;cursor:not-allowed}
.ozf-dots{padding:0 2px;opacity:.5}
.ozf-pageinfo{flex-basis:100%;text-align:center;opacity:.55;font-size:11px;padding-top:2px}
.ozf-foot{display:flex;justify-content:center;gap:4px;flex-wrap:wrap;padding:6px 0 2px;border-top:1px solid #ffffff14;margin-top:4px}
.ozf-foot a{color:inherit;opacity:.65;text-decoration:none;font-size:11px}
.ozf-foot a:hover{opacity:1;text-decoration:underline}
.ozf-batch-bar{display:flex;align-items:center;gap:6px;padding:4px 6px}
.ozf-btn-batch{border:none;border-radius:6px;padding:5px 10px;font-size:11.5px;cursor:pointer;background:#0b8043;color:#fff;flex:0 0 auto}
.ozf-btn-batch[disabled]{opacity:.5;cursor:wait}
.ozf-upgrade-btn{background:none;border:none;color:inherit;opacity:.65;cursor:pointer;font-size:11px;padding:0 4px}
.ozf-upgrade-btn:hover{opacity:1;text-decoration:underline}
.ozf-overlay{position:fixed;inset:0;z-index:100000;background:rgba(0,0,0,.55);display:flex;align-items:center;justify-content:center;padding:20px}
.ozf-dialog{max-width:520px;width:100%;max-height:80vh;overflow:auto;background:#20232a;border:1px solid #ffffff22;border-radius:12px;padding:16px;color:#e8eaf0;font:13px/1.6 system-ui,sans-serif}
.ozf-dialog h3{margin:0 0 8px;font-size:14px}
.ozf-dialog p{opacity:.8;margin:0 0 10px}
.ozf-dialog pre{background:#12141a;border-radius:8px;padding:10px;overflow:auto;font:11px/1.5 ui-monospace,Menlo,Consolas,monospace}
.ozf-dialog .ozf-actions{flex-direction:row;justify-content:flex-end;gap:8px;margin-top:10px}
.ozf-dialog .ozf-actions .ozf-btn{padding:6px 14px}
/* ---- 公告栏 ---- */
.ozf-announce{margin:0 0 8px;padding:8px 10px;border-radius:8px;font-size:12px;line-height:1.6;background:rgba(11,128,67,.12);border:1px solid #0b804355;color:#7ce0ac;word-break:break-word}
.ozf-announce a{color:inherit;text-decoration:underline}
/* ---- 文章区 ---- */
.ozf-articles{margin-top:10px;border-top:1px solid #ffffff14;padding-top:8px}
.ozf-articles-title{font-weight:600;font-size:12px;opacity:.8;margin:0 0 4px}
.ozf-article{display:flex;align-items:flex-start;gap:6px;width:100%;text-align:left;background:none;border:none;color:inherit;font:inherit;cursor:pointer;padding:6px 6px;border-radius:8px}
.ozf-article:hover{background:rgba(127,127,127,.09)}
.ozf-article-title{flex:1 1 auto;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.ozf-article-meta{flex:0 0 auto;font-size:10.5px;opacity:.5;white-space:nowrap}
.ozf-article-badges{display:inline}
/* ---- 文章详情浮窗 ---- */
.ozf-awin{position:fixed;right:18px;top:20px;left:auto;width:min(520px,92vw);height:min(560px,84vh);z-index:100010;background:#1b1d23;border:1px solid #ffffff22;border-radius:12px;box-shadow:-8px 12px 40px rgba(0,0,0,.5);display:flex;flex-direction:column;overflow:hidden;resize:both;min-width:300px;min-height:220px}
.ozf-awin.max{inset:0;left:0;top:0;right:0;bottom:0;width:100vw;height:100vh;max-width:none;max-height:none;border-radius:0;transform:none}
.ozf-awin.min{width:min(360px,80vw);height:auto;min-height:0}
.ozf-awin-head{display:flex;align-items:center;gap:6px;padding:8px 10px;border-bottom:1px solid #ffffff14;color:#e8eaf0;font-weight:600;font-size:12.5px;flex:0 0 auto;cursor:move;background:#23262d}
.ozf-awin-head .ozf-awin-t{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.ozf-awin-ctl{display:flex;gap:2px}
.ozf-awin-ctl button{background:none;border:none;color:inherit;opacity:.65;cursor:pointer;font-size:12px;padding:2px 6px;border-radius:6px;width:24px;height:24px;line-height:1}
.ozf-awin-ctl button:hover{opacity:1;background:rgba(255,255,255,.08)}
.ozf-awin-body{flex:1;overflow:hidden;display:flex;flex-direction:column;position:relative;background:#14161b}
.ozf-awin-body.loading{align-items:center;justify-content:center;color:#8b93a3;font-size:12px}
.ozf-awin iframe{width:100%;height:100%;border:none;background:#fff;display:block}
.ozf-awin.min .ozf-awin-body{display:none}
.ozf-awin.min .ozf-awin-resize{display:none}
.ozf-awin-resize{position:absolute;right:0;bottom:0;width:16px;height:16px;cursor:se-resize;background:linear-gradient(135deg,transparent 50%,#ffffff33 50%);z-index:2}
.ozf-tabs{display:flex;gap:4px;border-bottom:1px solid #ffffff22;margin:0;padding:6px 8px 0;flex:0 0 auto}
.ozf-tab{padding:6px 12px;cursor:pointer;border:1px solid transparent;border-bottom:none;border-radius:6px 6px 0 0;background:none;color:inherit;font-size:12px}
.ozf-tab.on{background:#1e2028;color:#8fb3ff}
.ozf-tab:hover{background:rgba(127,127,127,.12)}
.ozf-art-body{display:none;flex:1;overflow:auto;padding:12px}
.ozf-art-body.on{display:flex;flex-direction:column}
.ozf-article-in{line-height:1.75;font-size:14px;color:#e8eaf0;max-width:72ch;margin:0 auto;width:100%;flex:1}
.ozf-awin.max .ozf-article-in{max-width:none;margin:0 auto}
.ozf-article-in p,.ozf-article-in div,.ozf-article-in li,.ozf-article-in blockquote{margin:6px 0}
.ozf-article-in img{max-width:100%;height:auto;border-radius:6px}
.ozf-article-in pre{background:#12141a;border-radius:8px;padding:10px;overflow:auto;font:12px/1.5 ui-monospace,Menlo,Consolas,monospace;color:#e2e4e9}
.ozf-article-in a{color:#8fb3ff}
.ozf-embed-frame{flex:1;width:100%;min-height:300px;border:none;border-radius:6px;background:#fff}
.ozf-embed-img,.ozf-embed-video{max-width:100%;max-height:100%;object-fit:contain;border-radius:6px;margin:auto}
.ozf-open-btn{color:#8fb3ff;font-size:12px;align-self:flex-start;margin-top:8px}
.ozf-awin-loading-txt{color:#8b93a3;font-size:12px;padding:10px}
.ozf-auth-overlay{position:fixed;inset:0;z-index:100020;background:rgba(0,0,0,.6);display:flex;align-items:center;justify-content:center;padding:20px;font:13px/1.6 system-ui,sans-serif}
.ozf-auth-box{position:relative;width:100%;max-width:380px;background:#1b1d23;color:#e8eaf0;border:1px solid #ffffff22;border-radius:14px;padding:20px;box-shadow:0 12px 48px rgba(0,0,0,.5)}
.ozf-auth-box h3{margin:0 0 6px;font-size:16px;padding-right:28px}
.ozf-auth-close{position:absolute;top:10px;right:10px;width:28px;height:28px;border:none;background:transparent;color:#9aa3b2;font-size:18px;line-height:1;cursor:pointer;border-radius:6px}
.ozf-auth-close:hover{background:#ffffff1a;color:#fff}
.ozf-auth-notice{margin:0 0 14px;padding:10px 12px;font-size:12px;line-height:1.6;color:#ffd9a8;background:#3a2a12;border:1px solid #6b4a1f;border-radius:8px;white-space:pre-wrap;word-break:break-word}
.ozf-auth-hint{margin:0 0 14px;font-size:12px;opacity:.7}
.ozf-auth-box label{display:block;margin-bottom:10px;font-size:12px;opacity:.85}
.ozf-auth-box input{width:100%;margin-top:4px;padding:8px 10px;border-radius:8px;border:1px solid #3a3f4a;background:#14161b;color:inherit;font-size:13px}
.ozf-auth-box input:focus{outline:2px solid #2f6fed66;border-color:#2f6fed}
.ozf-auth-err{min-height:16px;margin:2px 0 8px;color:#ff9d9d;font-size:12px}
.ozf-auth-submit{width:100%;border:none;border-radius:8px;padding:10px;font-size:14px;cursor:pointer;background:linear-gradient(135deg,#0b8043,#1e9e5a);color:#fff}
`

function ensureStyle() {
  if (!document.getElementById('ozf-style')) {
    document.head.appendChild(el('style', { id: 'ozf-style', text: CSS }))
  }
}

/* ------------------------------------------------------------------ widget */
function apply(ctx) {
  const cfg = resolveClientConfig(ctx)
  ensureStyle()

  const state = {
    backendUrl: cfg.backendUrl,
    pageSize: cfg.pageSize,
    page: 1,
    data: null,
    loading: false,
    error: '',
    expanded: new Set(),
    applied: new Set(),
    // 文章 / 公告 / 标题
    panelTitle: '',
    announcement: '',
    articles: [],
    articlePage: 1,
    articleTotalPages: 1,
    articlesLoaded: false,
    articleError: '',
  }

  const toastWrap = el('div', { class: 'ozf-toast-wrap' })
  function toast(message, kind = 'ok') {
    const t = el('div', { class: `ozf-toast ${kind}`, text: message })
    toastWrap.appendChild(t)
    setTimeout(() => t.remove(), 3500)
  }

  const listEl = el('ul', { class: 'ozf-list' })
  const stateEl = el('div', { class: 'ozf-state' })
  const authStatusEl = el('div', { class: 'ozf-auth-status' })
  const bannerEl = el('div', { class: 'ozf-banner', text: STR.paused })
  const pagerEl = el('nav', { class: 'ozf-pager', 'aria-label': 'pagination' })

  // 公告栏 + 文章区
  const announceEl = el('div', { class: 'ozf-announce' })
  const articlesListEl = el('div', { class: 'ozf-articles-list' })
  const articlesPagerEl = el('nav', { class: 'ozf-pager', 'aria-label': 'articles' })
  const articlesWrap = el('section', { class: 'ozf-articles' }, [
    el('div', { class: 'ozf-articles-title', text: STR.articlesTitle }),
    articlesListEl,
    articlesPagerEl,
  ])

  const setupInput = el('input', {
    type: 'url', placeholder: STR.setupPlaceholder, spellcheck: 'false',
    onkeydown: (ev) => { if (ev.key === 'Enter') saveSetup() },
  })
  const setupBox = el('div', { class: 'ozf-setup' }, [
    el('p', { text: STR.setupHint }),
    setupInput,
    el('button', { type: 'button', onclick: saveSetup, text: STR.setupSave }),
  ])

  const upgradeBtn = el('button', {
    class: 'ozf-upgrade-btn', type: 'button', text: STR.upgradeBtn,
    onclick: () => checkUpgrade(),
  })
  const footEl = el('footer', { class: 'ozf-foot' }, [
    ...cfg.footerLinks.map((l, i) => {
      const link = el('a', { href: l.url, target: '_blank', rel: 'noopener noreferrer', text: l.label })
      return i === 0 ? link : [el('span', { class: 'ozf-dots', text: '·' }), link]
    }),
    el('span', { class: 'ozf-dots', text: '·' }),
    upgradeBtn,
  ])

  const batchBtn = el('button', {
    class: 'ozf-btn-batch', type: 'button', text: STR.batchBtn,
    onclick: () => batchApplyAll(),
  })
  const refreshBtn = el('button', {
    class: 'ozf-btn-batch', type: 'button', text: STR.refreshBtn, style: 'background:#34c77b',
    onclick: () => { state.expanded.clear(); state.articlesLoaded = false; loadPage(state.page); loadArticles(1) },
  })
  const batchBar = el('div', { class: 'ozf-batch-bar' }, [batchBtn, refreshBtn])

  const bodyEl = el('div', { class: 'ozf-body' }, [    bannerEl, announceEl, setupBox, stateEl, authStatusEl, batchBar, listEl, pagerEl, articlesWrap, footEl])
  const root = el('section', { class: 'ozf-panel' }, [bodyEl])
  document.body.appendChild(toastWrap)

  function saveSetup() {
    const url = safeHttpUrl(setupInput.value)
    if (!url) { toast(STR.badSource, 'err'); return }
    state.backendUrl = url.replace(/\/+$/, '')
    saveLocalOverride(state.backendUrl)
    setupBox.style.display = 'none'
    loadPage(1)
    loadArticles(1)
  }

  /* ---- rendering ---- */
  function renderState() {
    setupBox.style.display = state.backendUrl ? 'none' : ''
    batchBar.style.display = (state.backendUrl && state.data && state.data.items.length > 0) ? '' : 'none'
    stateEl.textContent = ''
    if (!state.backendUrl) { stateEl.textContent = ''; return }
    if (state.loading) {
      stateEl.className = 'ozf-state'
      stateEl.appendChild(el('div', { class: 'ozf-skel' }))
      stateEl.appendChild(el('div', { class: 'ozf-skel' }))
      stateEl.appendChild(el('div', { class: 'ozf-skel' }))
      return
    }
    if (state.error) {
      stateEl.className = 'ozf-state'
      stateEl.appendChild(el('div', { text: `${STR.errNet}${state.error}` }))
      stateEl.appendChild(el('div', { text: STR.errCors }))
      stateEl.appendChild(el('button', { class: 'ozf-retry', type: 'button', onclick: () => loadPage(state.page), text: STR.retry }))
      return
    }
    if (state.data && state.data.total === 0) stateEl.textContent = STR.empty
    bannerEl.style.display = (state.data && state.data.globalEnabled === false) ? '' : 'none'
  }

  function renderDetail(item) {
    const { pid } = buildProviderEntry({ prefix: cfg.providerIdPrefix, title: item.title, apiBase: item.apiBase, modelIds: item.modelIds, rowId: item.id })
    const applied = state.applied.has(pid)
    const codeBase = el('code', { text: item.apiBase })
    const modelsText = Array.isArray(item.modelIds) ? item.modelIds.join(', ') : ''
    const globalOn = !state.data || state.data.globalEnabled !== false
    const isFree = item.free === true
    const canInsert = globalOn && item.usable !== false && item.status !== 'disabled' && !isFree

    const applyBtn = el('button', {
      class: 'ozf-btn ' + (applied ? 'ozf-btn-remove' : 'ozf-btn-apply'), type: 'button',
      text: applied ? STR.removeBtn : STR.applyBtn,
      onclick: async (ev) => {
        // 同步捕获按钮引用：事件对象在首个 await 之后会清空 currentTarget。
        const btn = ev.currentTarget
        // 免费模型：禁用一键置入（如需启用请在后台将该模型标记为收费）。
        if (!applied && isFree) { toast(STR.freeModel, 'ok'); return }
        // 未授权时，点击“使用/应用”免费模型须先完成授权。
        // 现场重新核验授权要求，避免依赖启动时可能失败的首次检测导致门禁失效。
        if (!applied && !currentAuthToken) {
          let required = authEnabled
          try {
            const st = await apiJson('license', { act: 'status' })
            required = !!(st && st.auth_enabled === true)
            authEnabled = required
            if (required && typeof st.message === 'string') authNotice = st.message
          } catch {
            // 后端不可达时按“需要授权”处理（fail closed），防止门禁被静默关闭
            required = true
            authEnabled = true
          }
          if (required) { showAuthModal(mountPanel, authNotice); return }
        }
        btn.disabled = true
        btn.textContent = STR.applying
        try { if (applied) await removeProvider(item); else await applyProvider(item) } finally { btn.disabled = false; btn.textContent = applied ? STR.removeBtn : STR.applyBtn }
      },
    })
    if (!applied && !canInsert) applyBtn.disabled = true

    const children = [
      el('div', { class: 'ozf-field' }, [
        el('b', { text: STR.apiLabel }),
        el('span', { class: 'ozf-code' }, [codeBase, el('button', { class: 'ozf-copy', type: 'button', title: 'copy', onclick: async () => toast(await copyText(item.apiBase) ? STR.copied : STR.copyFail), text: '⧉' })]),
      ]),
      el('div', { class: 'ozf-field' }, [
        el('b', { text: STR.modelLabel }),
        el('span', { class: 'ozf-code' }, [el('code', { text: modelsText, title: modelsText }), el('button', { class: 'ozf-copy', type: 'button', title: 'copy', onclick: async () => toast(await copyText(modelsText) ? STR.copied : STR.copyFail), text: '⧉' })]),
      ]),
    ]
    if (!item.keyUrl) children.push(el('div', { class: 'ozf-note' + (canInsert ? '' : ' warn'), text: STR.noKey }))
    if (isFree) children.push(el('div', { class: 'ozf-note', text: STR.freeModel }))

    let statusText = ''
    if (!globalOn) statusText = STR.paused
    else if (item.status === 'disabled') statusText = STR.disabled
    else if (item.usable === false) {
      const fromTs = item.availableFrom ? Date.parse(item.availableFrom.replace(' ', 'T')) : 0
      statusText = (fromTs && fromTs > Date.now()) ? STR.notStarted : STR.expired
    }
    if (statusText) children.push(el('div', { class: 'ozf-note warn', text: statusText }))
    if (item.availableFrom || item.availableUntil) {
      children.push(el('div', { class: 'ozf-window', text: STR.windowLabel(item.availableFrom, item.availableUntil) }))
    }
    const keyBtn = item.keyUrl
      ? el('a', { class: 'ozf-btn ozf-btn-key', href: item.keyUrl, target: '_blank', rel: 'noopener noreferrer', text: STR.applyKeyBtn })
      : null
    children.push(el('div', { class: 'ozf-actions' }, keyBtn ? [keyBtn, applyBtn] : [applyBtn]))
    return el('div', { class: 'ozf-detail', dataset: { ozfId: String(item.id) } }, children)
  }

  function renderList() {
    listEl.textContent = ''
    if (!state.data || state.loading || state.error) return
    const offset = (state.data.page - 1) * state.data.pageSize
    state.data.items.forEach((item, idx) => {
      const key = String(item.id)
      const detail = renderDetail(item)
      if (state.expanded.has(key)) detail.classList.add('open')
      const title = el('button', {
        class: 'ozf-row-title', type: 'button',
        'aria-expanded': state.expanded.has(key) ? 'true' : 'false',
        onclick: () => {
          if (state.expanded.has(key)) state.expanded.delete(key)
          else state.expanded.add(key)
          detail.classList.toggle('open')
          title.setAttribute('aria-expanded', detail.classList.contains('open') ? 'true' : 'false')
        },
      }, [
        el('span', { class: 'ozf-rank', text: `${offset + idx + 1}.` }),
        el('span', { class: 'ozf-name', title: item.title }, [
          item.pinned ? el('span', { text: '📌' }) : null,
          item.title,
          item.badge === 'hot' ? el('span', { class: 'ozf-badge hot', text: STR.badgeHot }) : null,
          item.badge === 'rec' ? el('span', { class: 'ozf-badge rec', text: STR.badgeRec }) : null,
          item.badge === 'free' ? el('span', { class: 'ozf-badge free', text: STR.badgeFree }) : null,
          item.badge === 'paid' ? el('span', { class: 'ozf-badge paid', text: STR.badgePaid }) : null,
          item.status === 'disabled' ? el('span', { class: 'ozf-badge off', text: STR.disabled }) : null,
          item.free === true && item.badge !== 'free' ? el('span', { class: 'ozf-badge free', text: STR.badgeFree }) : null,
        ]),
        el('span', { class: 'ozf-caret', text: '›' }),
      ])
      listEl.appendChild(el('li', { class: 'ozf-row' }, [title, detail]))
    })
  }

  function renderPager() {
    pagerEl.textContent = ''
    if (!state.data || state.loading || state.error || state.data.totalPages <= 0) return
    const { page, totalPages } = state.data
    if (totalPages <= 1) return
    const mk = (label, target, opts = {}) => {
      const disabled = opts.disabled === true
      return el('button', {
        type: 'button', text: label, disabled,
        'aria-label': opts.aria || label,
        ...(opts.current ? { 'aria-current': 'true' } : {}),
        onclick: disabled || opts.current ? undefined : () => loadPage(target),
      })
    }
    pagerEl.appendChild(mk('«', 1, { aria: STR.first, disabled: page <= 1 }))
    pagerEl.appendChild(mk('‹', page - 1, { aria: STR.prev, disabled: page <= 1 }))
    for (const part of pageWindow(page, totalPages)) {
      if (part === '…') pagerEl.appendChild(el('span', { class: 'ozf-dots', text: '…' }))
      else pagerEl.appendChild(mk(String(part), part, { current: part === page }))
    }
    pagerEl.appendChild(mk('›', page + 1, { aria: STR.next, disabled: page >= totalPages }))
    pagerEl.appendChild(mk('»', totalPages, { aria: STR.last, disabled: page >= totalPages }))
    pagerEl.appendChild(el('span', { class: 'ozf-pageinfo', text: STR.pageInfo(state.data.total, page, totalPages) }))
  }

  /* ---- 公告栏 / 文章 ---- */
  function renderAnnounce() {
    const text = (state.announcement || '').trim()
    announceEl.style.display = text ? '' : 'none'
    announceEl.textContent = ''
    if (!text) return
    const nodes = linkify(text).nodes
    announceEl.append(...nodes)
  }

  /** 把纯文本里的 URL 转成可点击链接（安全；目标加新窗口）。 */
  function linkify(text) {
    const nodes = []
    const urlRe = /(https?:\/\/[^\s<>"']+)/g
    let last = 0
    let m
    const src = String(text)
    while ((m = urlRe.exec(src)) !== null) {
      if (m.index > last) nodes.push(el('span', { text: src.slice(last, m.index) }))
      const u = safeHttpUrl(m[0])
      nodes.push(u
        ? el('a', { href: u, target: '_blank', rel: 'noopener noreferrer', text: m[0] })
        : el('span', { text: m[0] }))
      last = urlRe.lastIndex
    }
    if (last < src.length) nodes.push(el('span', { text: src.slice(last) }))
    return { nodes }
  }

  function renderArticles() {
    articlesWrap.style.display = (state.loading && !state.articlesLoaded) ? 'none' : ''
    // 无后端 / 尚未加载时隐藏文章区
    if (!state.backendUrl || !state.articlesLoaded) { articlesWrap.style.display = 'none'; return }
    articlesListEl.textContent = ''
    if (state.articles.length === 0) {
      articlesListEl.appendChild(el('div', { class: 'ozf-state', text: state.articleError ? `${STR.articleErr} ${state.articleError}` : STR.articlesEmpty }))
    }
    state.articles.forEach((article) => {
      const extUrl = safeHttpUrl(article.link_url || '')
      const badges = el('span', { class: 'ozf-article-badges' }, [
        article.pinned ? el('span', { text: '📌' }) : null,
        article.hot ? el('span', { text: '🔥' }) : null,
        article.rec ? el('span', { text: '⭐' }) : null,
        extUrl ? el('span', { text: '🔗' }) : null,
      ])
      const row = el('button', {
        class: 'ozf-article' + (extUrl ? ' ozf-article-ext' : ''), type: 'button',
        onclick: () => {
          if (extUrl) {
            const a = document.createElement('a')
            a.href = extUrl
            a.target = '_blank'
            a.rel = 'noopener noreferrer'
            document.body.appendChild(a)
            a.click()
            a.remove()
            return
          }
          openArticle(article.id, article.title)
        },
      }, [
        el('span', { class: 'ozf-article-title', title: article.title }, [badges, article.title]),
        article.publishedAt ? el('span', { class: 'ozf-article-meta', text: article.publishedAt.slice(0, 10) }) : null,
      ])
      articlesListEl.appendChild(row)
    })
    renderArticlesPager()
  }

  function renderArticlesPager() {
    articlesPagerEl.textContent = ''
    if (state.articleTotalPages <= 1) return
    const { articlePage, articleTotalPages } = state
    const mk = (label, target, opts = {}) => {
      const disabled = opts.disabled === true
      return el('button', {
        type: 'button', text: label, disabled,
        'aria-label': opts.aria || label,
        ...(opts.current ? { 'aria-current': 'true' } : {}),
        onclick: disabled || opts.current ? undefined : () => loadArticles(target),
      })
    }
    articlesPagerEl.appendChild(mk('‹', articlePage - 1, { aria: STR.prev, disabled: articlePage <= 1 }))
    for (const part of pageWindow(articlePage, articleTotalPages)) {
      if (part === '…') articlesPagerEl.appendChild(el('span', { class: 'ozf-dots', text: '…' }))
      else articlesPagerEl.appendChild(mk(String(part), part, { current: part === articlePage }))
    }
    articlesPagerEl.appendChild(mk('›', articlePage + 1, { aria: STR.next, disabled: articlePage >= articleTotalPages }))
  }

  /* ---- 文章详情浮窗（最大化 / 最小化 / 关闭） ---- */
  let modalWin = null
  function openArticle(id, fallbackTitle) {
    closeArticleModal()
    const win = el('div', { class: 'ozf-awin' })
    const head = el('div', { class: 'ozf-awin-head' })
    const titleEl = el('span', { class: 'ozf-awin-t', text: fallbackTitle })
    const ctl = el('div', { class: 'ozf-awin-ctl' }, [
      el('button', { type: 'button', text: '–', title: STR.minimize, onclick: () => { win.classList.add('min') } }),
      el('button', { type: 'button', text: '⛶', title: STR.maximize, onclick: () => { win.classList.remove('min'); win.classList.toggle('max'); win.style.left = ''; win.style.top = ''; win.style.width = ''; win.style.height = ''; win.style.right = '' } }),
      el('button', { type: 'button', text: '✕', title: STR.close, onclick: () => closeArticleModal() }),
    ])
    const body = el('div', { class: 'ozf-awin-body' })
    head.append(titleEl, ctl)
    win.append(head, body, el('div', { class: 'ozf-awin-resize' }))
    modalWin = win
    document.body.appendChild(win)
    track('article', 'article_open', String(id))
    // Q1: 窗口默认定位到屏幕中央（文章内容也居中），可自由拖拽 / 最大化 / 拉伸。
    const dw = Math.min(520, window.innerWidth * 0.92)
    const dh = Math.min(560, window.innerHeight * 0.84)
    win.style.left = Math.max(8, Math.round((window.innerWidth - dw) / 2)) + 'px'
    win.style.top = Math.max(8, Math.round((window.innerHeight - dh) / 2)) + 'px'
    win.style.right = 'auto'
    dragMove(win, head)
    const tabs = el('div', { class: 'ozf-tabs' })
    const contentTab = el('button', { class: 'ozf-tab on', type: 'button', text: STR.tabContent })
    const linkTab = el('button', { class: 'ozf-tab', type: 'button', text: STR.tabLink })
    tabs.appendChild(contentTab)
    const contentPane = el('div', { class: 'ozf-art-body on' })
    contentPane.appendChild(el('div', { class: 'ozf-article-in' }, [el('div', { class: 'ozf-awin-loading-txt', text: STR.articleLoading })]))
    let linkPane = null
    function selectTab(which) {
      contentTab.classList.toggle('on', which === 'content')
      linkTab.classList.toggle('on', which === 'link')
      contentPane.classList.toggle('on', which === 'content')
      if (linkPane) linkPane.classList.toggle('on', which === 'link')
    }
    contentTab.addEventListener('click', () => selectTab('content'))
    linkTab.addEventListener('click', () => selectTab('link'))
    body.appendChild(tabs)
    body.appendChild(contentPane)
    fetchArticleDetail(id).then((article) => {
      if (modalWin !== win) return
      titleEl.textContent = article.title || fallbackTitle
      const content = String(article.content || article.excerpt || '').trim()
      const linkUrl = article.linkUrl || ''
      const contentIn = contentPane.querySelector('.ozf-article-in')
      if (contentIn) contentIn.innerHTML = sanitizeHtml(content) || '<p>（暂无正文，可点击「链接」标签在浏览器查看原文）</p>'
      if (linkUrl) {
        const kind = linkKind(linkUrl)
        linkPane = el('div', { class: 'ozf-art-body' })
        const openLink = el('a', { class: 'ozf-open-btn', href: linkUrl, target: '_blank', rel: 'noopener noreferrer', text: STR.openNew })
        if (kind === 'image') {
          linkPane.appendChild(el('img', { class: 'ozf-embed-img', src: linkUrl, alt: '', referrerpolicy: 'no-referrer' }))
          linkPane.appendChild(openLink)
        } else if (kind === 'video') {
          linkPane.appendChild(el('video', { class: 'ozf-embed-video', src: linkUrl, controls: true }))
          linkPane.appendChild(openLink)
        } else {
          linkPane.appendChild(el('div', { class: 'ozf-link-hint' }, [
            el('span', { text: '该链接为网页，请点击在浏览器中打开：' }),
            openLink,
          ]))
        }
        body.appendChild(linkPane)
        if (!linkTab.parentNode) tabs.appendChild(linkTab)
      }
      const off = (ev) => { if (ev.key === 'Escape') closeArticleModal(); document.removeEventListener('keydown', off) }
      document.addEventListener('keydown', off)
    }).catch(() => {
      if (modalWin !== win) return
      body.textContent = ''
      body.className = 'ozf-awin-body'
      body.appendChild(el('div', { class: 'ozf-awin-loading-txt', text: STR.articleErr }))
    })
  }

  function closeArticleModal() {
    if (modalWin) { modalWin.remove(); modalWin = null }
  }

  function dragMove(win, handle) {
    let sx = 0, sy = 0, ox = 0, oy = 0, dragging = false
    handle.addEventListener('mousedown', (e) => {
      if (win.classList.contains('min')) return
      // Q2: 拖动已最大化的窗口时，先“解除最大化”变成可自由移动的普通大窗口，再跟随鼠标。
      if (win.classList.contains('max')) {
        const r = win.getBoundingClientRect()
        // 保留 max 类，使文章内容在拖拽后仍保持最大化全宽；用内联盒模型覆盖 inset 以可自由拖动。
        win.style.left = r.left + 'px'
        win.style.top = r.top + 'px'
        win.style.width = Math.max(r.width, 420) + 'px'
        win.style.height = Math.max(r.height, 360) + 'px'
        win.style.right = 'auto'
      }
      dragging = true
      sx = e.clientX; sy = e.clientY
      const r = win.getBoundingClientRect()
      ox = r.left; oy = r.top
      const move = (ev) => {
        if (!dragging) return
        win.style.left = `${ox + (ev.clientX - sx)}px`
        win.style.top = `${oy + (ev.clientY - sy)}px`
        win.style.right = 'auto'
      }
      const up = () => { dragging = false; document.removeEventListener('mousemove', move); document.removeEventListener('mouseup', up) }
      document.addEventListener('mousemove', move)
      document.addEventListener('mouseup', up)
    })
  }

  function wrapArticleHtml(article) {
    const title = String(article.title || '').replace(/</g, '&lt;')
    return `<!DOCTYPE html><html><head><meta charset="utf-8">
<meta name="referrer" content="no-referrer">
<style>
body{font:14px/1.8 system-ui,"Segoe UI","Microsoft YaHei",sans-serif;color:#1c1e21;margin:0;padding:18px 20px;background:#fff}
h1,h2,h3,h4{margin:14px 0 8px;line-height:1.4}
h1{font-size:20px;border-bottom:1px solid #eee;padding-bottom:8px}
p{margin:8px 0}
a{color:#2f6fed}
img{max-width:100%;height:auto;border-radius:6px}
pre{background:#f4f5f7;border:1px solid #e4e7ec;border-radius:8px;padding:10px;overflow:auto;font:12.5px/1.6 ui-monospace,Consolas,monospace}
code{background:#f4f5f7;border-radius:4px;padding:1px 5px;font-size:12.5px}
blockquote{border-left:3px solid #ccd1d9;margin:8px 0;padding:2px 12px;color:#666}
table{border-collapse:collapse;margin:8px 0}
td,th{border:1px solid #dde1e7;padding:5px 9px}
</style></head><body>${article.content || '<p>（空内容）</p>'}</body></html>`
  }

  function parseArticlesResponse(payload) {
    const p = (payload && typeof payload === 'object') ? payload : {}
    const items = Array.isArray(p.items)
      ? p.items
      : (Array.isArray(p.articles) ? p.articles : [])
    return {
      panelTitle: typeof p.panel_title === 'string' ? p.panel_title : '',
      announcement: typeof p.announcement === 'string' ? p.announcement : '',
      articles: items,
      articleTotalPages: p.total_pages ? (parseInt(p.total_pages, 10) || 1) : 1,
    }
  }

  async function loadArticles(page) {
    if (!state.backendUrl) return
    const url = articlesEndpoint()
    if (!url) { state.articleError = STR.articleErr; state.articlesLoaded = true; renderArticles(); return }
    state.articlePage = page
    const ctrl = new AbortController()
    const t = setTimeout(() => ctrl.abort(), cfg.requestTimeoutMs)
    try {
      const res = await fetch(`${url}${url.includes('?') ? '&' : '?'}page=${page}&page_size=8`, { signal: ctrl.signal, credentials: 'omit', headers: { Accept: 'application/json' } })
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      const payload = await res.json()
      const parsed = parseArticlesResponse(payload)
      if (parsed.panelTitle) state.panelTitle = parsed.panelTitle
      if (parsed.announcement) state.announcement = parsed.announcement
      state.articles = parsed.articles
      state.articleTotalPages = parsed.articleTotalPages
      state.articlesLoaded = true
      state.articleError = ''
      renderTitle()
      renderAnnounce()
    } catch (error) {
      state.articlesLoaded = true
      state.articleError = (error && error.name === 'AbortError') ? '(timeout)' : `(${error && error.message})`
    } finally {
      clearTimeout(t)
      renderArticles()
    }
  }

  async function fetchArticleDetail(id) {
    const idStr = String(id)
    // 后端列表接口只返回 excerpt，完整正文需走独立详情接口（?id=）。优先用列表里
    // 已带的 content（若后台列表也返回了），否则请求详情接口拿全文，最后回退到 excerpt。
    const cached = (state.articles || []).find((a) => String(a && a.id) === idStr)
    if (cached && cached.content && String(cached.content).trim()) {
      return {
        title: String(cached.title || ''),
        content: String(cached.content || ''),
        linkUrl: safeHttpUrl(String(cached.link_url || '')),
      }
    }
    const url = articlesEndpoint()
    const detailUrl = url + (url.includes('?') ? '&' : '?') + 'id=' + encodeURIComponent(idStr)
    const ctrl = new AbortController()
    const t = setTimeout(() => ctrl.abort(), cfg.requestTimeoutMs)
    try {
      if (!url) throw new Error('no endpoint')
      const res = await fetch(detailUrl, { signal: ctrl.signal, credentials: 'omit', headers: { Accept: 'application/json' } })
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      const payload = await res.json()
      const article = (payload && payload.article) || null
      if (!article) throw new Error('not found')
      return {
        title: String(article.title || ''),
        content: String(article.content || article.excerpt || (cached && cached.excerpt) || ''),
        linkUrl: safeHttpUrl(String(article.link_url || '')),
      }
    } finally {
      clearTimeout(t)
    }
  }

  function articlesEndpoint() {
    try {
      const base = state.backendUrl.replace(/\/+$/, '')
      const u = new URL(base)
      const p = u.pathname.replace(/\/+$/, '')
      if (/\.php$/i.test(p)) u.pathname = p.replace(/\.php$/i, '_articles.php')
      else u.pathname = `${p}/api/articles`
      return u.toString()
    } catch {
      return ''
    }
  }

  let titleRefs = []
  function registerTitle(elRef) { titleRefs.push(elRef) }
  function renderTitle() {
    const t = (state.panelTitle && state.panelTitle.trim()) ? state.panelTitle : STR.panelTitle
    titleRefs.forEach((r) => { if (r) r.textContent = `🎁 ${t}` })
  }

  function renderAll() { renderState(); renderList(); renderPager(); renderAnnounce(); renderArticles(); renderTitle() }

  /* ---- data ---- */
  let seq = 0
  let timer = null
  let apiEndpoint = ''

  async function fetchModels(endpoint, signal) {
    const res = await fetch(endpoint, { signal, credentials: 'omit', headers: { Accept: 'application/json' } })
    if (!res.ok) throw Object.assign(new Error(`HTTP ${res.status}`), { ozfTryNext: res.status >= 400 && res.status < 500 })
    const payload = await res.json()
    const data = parseModelsResponse(payload, state.pageSize)
    return { data, endpoint }
  }

  async function loadPage(page) {
    if (!state.backendUrl) { renderAll(); return }
    const mySeq = ++seq
    state.loading = true
    state.error = ''
    state.page = page
    state.expanded.clear()
    renderAll()
    const ctrl = new AbortController()
    timer = setTimeout(() => ctrl.abort(), cfg.requestTimeoutMs)
    try {
      const candidates = apiEndpoint ? [apiEndpoint] : apiCandidates(state.backendUrl)
      let lastError = null
      let result = null
      for (const endpoint of candidates) {
        try {
          result = await fetchModels(endpoint, ctrl.signal)
          apiEndpoint = endpoint
          break
        } catch (error) {
          lastError = error
          if (error && error.name === 'AbortError') throw error
          if (!(error && error.ozfTryNext) && candidates.length === 1) throw error
        }
      }
      if (!result) throw lastError || new Error('no endpoint')
      if (mySeq !== seq) return
      state.data = result.data
      state.loading = false
      try { await refreshApplied() } catch (e) { dbg('refreshApplied failed:', e && e.message) }
    } catch (error) {
      if (mySeq !== seq) return
      state.loading = false
      state.error = error && error.name === 'AbortError' ? '(timeout)' : `(${error && error.message})`
      dbg('fetch failed:', error && error.message)
    } finally {
      clearTimeout(timer)
      if (mySeq === seq) renderAll()
    }
  }

  /* ---- provider write (through DSH settingsScope) ---- */
  async function getBoundNamespace(namespace) {
    try {
      const scope = ctx && ctx.settingsScope
      if (scope && typeof scope.bind === 'function') return scope.bind({ namespace })
    } catch (error) {
      dbg('settingsScope bind failed:', error && error.message)
    }
    return null
  }

  async function readProviders(bound) {
    if (!bound) return {}
    try {
      if (typeof bound.load === 'function') await bound.load().catch(() => {})
      let v = null
      if (typeof bound.getSnapshot === 'function') {
        const snap = bound.getSnapshot()
        v = (snap && (snap.value || snap.base)) || null
      }
      if ((!v || typeof v !== 'object') && (bound.value || bound.base)) v = bound.value || bound.base
      const providers = v && v.providers
      return providers && typeof providers === 'object' ? { ...providers } : {}
    } catch {
      return {}
    }
  }

  function showFallbackDialog(pid, entry) {
    const yaml = toYamlSnippet({ pid, entry })
    const close = () => overlay.remove()
    const overlay = el('div', {
      class: 'ozf-overlay',
      onclick: (ev) => { if (ev.target === overlay) close() },
    }, [el('div', { class: 'ozf-dialog', role: 'dialog', 'aria-modal': 'true' }, [
      el('h3', { text: STR.fallbackTitle }),
      el('p', { text: STR.fallbackBody }),
      el('pre', {}, [el('code', { text: yaml })]),
      el('div', { class: 'ozf-actions' }, [
        el('button', { class: 'ozf-btn', type: 'button', onclick: async () => toast(await copyText(yaml) ? STR.copied : STR.copyFail), text: STR.fallbackCopy }),
        el('button', { class: 'ozf-btn ozf-btn-apply', type: 'button', onclick: close, text: STR.fallbackClose }),
      ]),
    ])])
    document.body.appendChild(overlay)
    const esc = (ev) => { if (ev.key === 'Escape') { close(); document.removeEventListener('keydown', esc) } }
    document.addEventListener('keydown', esc)
  }

  // dsh-opencode-free-models no longer writes providers. The free models are
  // provided automatically by this plugin's opencode-free host adapter (they
  // appear directly in the model selector), so the panel is browse-only.
  // Writing opencode-* providers into llm-pi-ai would collide with
  // dsh-opencode-zen (which uses the opencode provider), hence disabled here.
  async function applyProvider(item) {
    const { pid } = buildProviderEntry({
      prefix: cfg.providerIdPrefix, title: item.title, apiBase: item.apiBase, modelIds: item.modelIds, rowId: item.id,
    })
    toast(`${pid} 已由本插件的 opencode-free provider 自动提供，直接在模型选择器选用即可（无需置入）`, 'ok')
  }

  async function removeProvider(item) {
    const { pid } = buildProviderEntry({ prefix: cfg.providerIdPrefix, title: item.title, apiBase: item.apiBase, modelIds: item.modelIds, rowId: item.id })
    // Provider writes are disabled (see applyProvider). Nothing to remove.
    toast(`${pid} 由本插件的 opencode-free provider 自动提供，无需取消置入`, 'ok')
    renderList()
  }

  async function refreshApplied() {
    // Provider writes are disabled; no provider is ever marked as applied here.
    state.applied = new Set()
    renderList()
  }

  async function batchApplyAll() {
    if (!state.data || !state.data.items.length) return
    if (state.data.globalEnabled === false) { toast(STR.paused, 'err'); return }
    // Provider writes are disabled (see applyProvider). Nothing is written.
    toast('这些免费模型已由本插件的 opencode-free provider 自动提供，直接在模型选择器选用即可', 'ok')
  }

  /* ---- upgrade check (against our own backend /api/version) ---- */
  const CURRENT_VERSION = '0.1.0'
  function versionUrl() {
    const base = state.backendUrl.replace(/\/+$/, '')
    try {
      const u = new URL(base)
      u.pathname = `${u.pathname.replace(/\/+$/, '')}/api/version`
      return u.toString()
    } catch { return '' }
  }
  async function checkUpgrade() {
    upgradeBtn.textContent = STR.upgradeChecking
    const url = versionUrl()
    try {
      if (!url) throw new Error('no backend')
      const res = await fetch(url, { headers: { Accept: 'application/json' } })
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      const data = await res.json()
      const latest = (data && typeof data.version === 'string') ? data.version.replace(/^v/, '') : ''
      if (!latest || latest === CURRENT_VERSION) toast(STR.upgradeLatest, 'ok')
      else toast(STR.upgradeNew(latest), 'ok')
    } catch (error) {
      dbg('upgrade check failed:', error && error.message)
      toast(STR.upgradeFailed, 'err')
    }
    upgradeBtn.textContent = STR.upgradeBtn
  }

  /* ---- mounting (right-edge drawer by default) ---- */
  function installRightDrawer() {
    const drawer = el('aside', { class: 'ozf-drawer', 'aria-label': STR.panelTitle })
    const headTitle = el('span', { text: `🎁 ${STR.panelTitle}` })
    registerTitle(headTitle)
    const head = el('div', { class: 'ozf-drawer-head' }, [
      headTitle,
      el('button', { class: 'ozf-drawer-close', type: 'button', text: '✕', title: STR.close, onclick: () => setOpen(false) }),
    ])
    const bodyWrap = el('div', { class: 'ozf-drawer-body' }, [root])
    drawer.appendChild(head)
    drawer.appendChild(bodyWrap)

    const launcher = el('button', {
      class: 'ozf-launcher', type: 'button', text: '🎁 免费模型', title: STR.launcherTitle, 'aria-label': STR.launcherTitle,
      onclick: () => {
        if (authEnabled && !currentAuthToken) { showAuthModal(mountPanel, authNotice); return }
        setOpen(!drawer.classList.contains('open'))
      },
    })

    function setOpen(open) {
      drawer.classList.toggle('open', open)
      try { localStorage.setItem(LS_OPEN, open ? '1' : '0') } catch { /* ignore */ }
    }
    const esc = (ev) => { if (ev.key === 'Escape') setOpen(false) }
    document.addEventListener('keydown', esc)
    document.body.appendChild(launcher)
    document.body.appendChild(drawer)
    let initial = false
    try { initial = localStorage.getItem(LS_OPEN) === '1' } catch { /* ignore */ }
    if (initial) setOpen(true)
    return () => {
      document.removeEventListener('keydown', esc)
      launcher.remove()
      drawer.remove()
    }
  }

  /* ============================================================
   * 授权门禁 + 流量埋点（新增功能）
   * ============================================================ */
  let currentAuthToken = ''
  let authEnabled = false
  let authNotice = ''
  let clientAuthorized = false
  let authOverlay = null
  let silentVerifyTimer = null
  function safeLocalGet(k) { try { return localStorage.getItem(k) || '' } catch { return '' } }
  function safeLocalSet(k, v) { try { localStorage.setItem(k, v) } catch { /* ignore */ } }
  function safeLocalDel(k) { try { localStorage.removeItem(k) } catch { /* ignore */ } }

  // Persist an operator authorization flag into our settingsScope so the host can
  // enable the free-provider (OPENCODE_ZEN_API_KEY) on the next startup. This is
  // what actually gates the "opencode免费模型" entry in the chat input selector.
  function markAuthorized() {
    try {
      const scope = ctx && ctx.settingsScope
      if (scope && typeof scope.bind === 'function') {
        const bound = scope.bind({ namespace: 'opencode-free-models' })
        if (bound && typeof bound.set === 'function') bound.set('authorized', true)
      }
    } catch { /* ignore */ }
  }

  // 在面板里直接显示授权/免费模型启用状态，免去找进程日志。
  function updateAuthStatus() {
    if (!authStatusEl) return
    authStatusEl.style.cssText = 'margin:8px 10px;padding:7px 10px;border-radius:8px;font-size:12px;line-height:1.5'
    if (authEnabled && !currentAuthToken) {
      authStatusEl.style.background = '#3a1414'; authStatusEl.style.color = '#ffb3b3'; authStatusEl.style.border = '1px solid #5a2020'
      authStatusEl.textContent = '⚠ 未授权：免费模型已锁定。请在弹出的授权表单填写信息+授权码完成授权；授权后立即生效，无需重启，「opencode免费模型」会出现在聊天输入框的模型选择器中。'
    } else if (currentAuthToken) {
      authStatusEl.style.background = '#10301c'; authStatusEl.style.color = '#9af0bd'; authStatusEl.style.border = '1px solid #1d5a36'
      authStatusEl.textContent = '✓ 已授权：「opencode免费模型」已在聊天输入框模型选择器中启用。'
    } else {
      authStatusEl.style.cssText = 'display:none'
      authStatusEl.textContent = ''
    }
  }

  /** 组合后端 API 地址：base + /api/<name>。 */
  function apiUrlOf(name, params) {
    const base = (cfg.backendUrl || '').replace(/\/+$/, '')
    let url = base + '/api/' + name
    if (params && Object.keys(params).length) {
      const qs = Object.keys(params).map((kk) => encodeURIComponent(kk) + '=' + encodeURIComponent(params[kk])).join('&')
      url += '?' + qs
    }
    return url
  }

  /** 基础 JSON 请求（GET 或带 body 的 POST）。 */
  async function apiJson(name, params, opts) {
    const ctrl = new AbortController()
    const t = setTimeout(() => ctrl.abort(), cfg.requestTimeoutMs || 10000)
    try {
      const res = await fetch(apiUrlOf(name, params), {
        signal: ctrl.signal, credentials: 'omit',
        headers: { Accept: 'application/json' }, ...(opts || {}),
      })
      if (!res.ok) throw new Error('HTTP ' + res.status)
      return await res.json()
    } finally { clearTimeout(t) }
  }

  /** 流量埋点：用 1x1 像素信标上报，失败不影响主流程。 */
  function track(kind, path, detail) {
    try {
      const p = new URLSearchParams({ kind: kind || 'pageview' })
      if (path) p.set('path', String(path).slice(0, 255))
      if (detail) p.set('detail', String(detail).slice(0, 255))
      const img = new Image()
      img.referrerPolicy = 'no-referrer'
      img.src = apiUrlOf('track', {}) + '?' + p.toString()
    } catch { /* 埋点失败忽略 */ }
  }

  const AUTH_TOKEN_KEY = 'ozf:auth:token'

  /** 未授权时展示授权弹窗：含后台配置的“未授权提示文案”与可关闭按钮。
   *  关闭后仍挂载面板（免费模型可见），但“使用”时会再次要求授权；
   *  关闭按钮仅隐藏本次弹窗，不持久化“不再提示”，下次进入仍未授权会重新弹出。 */
  function showAuthModal(mount, message) {
    function dismiss() {
      overlay.remove()
      authOverlay = null
      mount()
    }
    const overlay = el('div', { class: 'ozf-auth-overlay' }, [
      el('div', { class: 'ozf-auth-box', role: 'dialog', 'aria-modal': 'true' }, [
        el('button', { class: 'ozf-auth-close', type: 'button', title: STR.close, text: '✕', onclick: dismiss }),
        el('h3', { text: STR.authTitle }),
        message
          ? el('div', { class: 'ozf-auth-notice', text: message })
          : el('p', { class: 'ozf-auth-hint', text: STR.authHint }),
        el('label', { text: STR.authName }, [el('input', { name: 'name', maxlength: '40', placeholder: STR.authName })]),
        el('label', { text: STR.authPhone }, [el('input', { name: 'phone', maxlength: '40', placeholder: STR.authPhone })]),
        el('label', { text: STR.authWechat }, [el('input', { name: 'wechat', maxlength: '60', placeholder: STR.authWechat })]),
        el('label', { text: STR.authEmail }, [el('input', { name: 'email', type: 'email', maxlength: '120', placeholder: STR.authEmail })]),
        el('label', { text: STR.authCode }, [el('input', { name: 'code', maxlength: '64', placeholder: STR.authCode })]),
        el('p', { class: 'ozf-auth-err', text: '' }),
        el('button', { class: 'ozf-auth-submit', type: 'button', text: STR.authSubmit, onclick: async (ev) => {
          const box = ev.currentTarget.closest('.ozf-auth-box')
          const name = box.querySelector('[name=name]').value.trim()
          const phone = box.querySelector('[name=phone]').value.trim()
          const wechat = box.querySelector('[name=wechat]').value.trim()
          const email = box.querySelector('[name=email]').value.trim()
          const code = box.querySelector('[name=code]').value.trim()
          const errEl = box.querySelector('.ozf-auth-err')
          if (!name || !phone || !wechat || !email || !code) { errEl.textContent = STR.authErrRequired; return }
          const btn = ev.currentTarget
          btn.disabled = true; btn.textContent = STR.authVerifying
          try {
            const r = await apiJson('license', null, {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({ act: 'activate', name, phone, wechat, email, code }),
            })
             if (r && r.ok) {
               safeLocalSet(AUTH_TOKEN_KEY, r.token || '1')
               currentAuthToken = r.token || '1'
               clientAuthorized = true
               writeAuthFlags(true, true)
               pushAuthState(true)
                updateAuthStatus()
               overlay.remove()
               authOverlay = null
               mount()
             } else {
              errEl.textContent = STR.authErrInvalid
            }
          } catch { errEl.textContent = STR.authErrNet }
          finally { btn.disabled = false; btn.textContent = STR.authSubmit }
        } }),
      ]),
    ])
    document.body.appendChild(overlay)
    authOverlay = overlay
  }

  async function runAuthGate(mount) {
    try {
      const st = await apiJson('license', { act: 'status' })
      const enabled = !!(st && st.auth_enabled === true)
      authEnabled = enabled
      authNotice = (st && typeof st.message === 'string') ? st.message : ''
      writeAuthFlags(enabled, false)
      pushAuthState(!enabled)
      if (!enabled) { clientAuthorized = true; pushAuthState(true); mount(); return }
      const saved = safeLocalGet(AUTH_TOKEN_KEY)
      if (saved) {
        try {
          const v = await apiJson('license', { act: 'verify', t: saved })
          if (v && v.ok) { currentAuthToken = saved; clientAuthorized = true; writeAuthFlags(true, true); pushAuthState(true); updateAuthStatus(); mount(); return }
        } catch { /* ignore */ }
        // 校验失败（如后台撤销）：保留本地 token，后台重新授权后由静默校验自动恢复，
        // 避免用户被迫重新填写表单。
        clientAuthorized = false
      }
      showAuthModal(mount, authNotice)
      startSilentVerify()
    } catch {
      authEnabled = true
      clientAuthorized = false
      writeAuthFlags(true, false)
      pushAuthState(false)
      mount()
    }
  }

  // 后台撤销/重新授权后，周期性用本地 token 静默重新校验；一旦后台恢复有效即自动
  // 标记为已授权、关闭授权弹窗并通知 host（无需用户重新填写表单）。
  const startSilentVerify = () => {
    if (silentVerifyTimer) return
    const tick = async () => {
      if (clientAuthorized) return
      const saved = safeLocalGet(AUTH_TOKEN_KEY)
      if (!saved) return
      try {
        const v = await apiJson('license', { act: 'verify', t: saved })
        if (v && v.ok) {
          currentAuthToken = saved
          clientAuthorized = true
          writeAuthFlags(true, true)
          pushAuthState(true)
          updateAuthStatus()
          if (authOverlay) { authOverlay.remove(); authOverlay = null }
        }
      } catch { /* ignore */ }
    }
    silentVerifyTimer = setInterval(tick, 30000)
    setTimeout(tick, 5000)
  }

  // 向 settingsScope 写入授权双标志供 host 读取：authRequired(是否需要授权) + authorized(已授权)
  function writeAuthFlags(authRequired, authorized) {
    try {
      const scope = ctx && ctx.settingsScope
      if (scope && typeof scope.bind === 'function') {
        const bound = scope.bind({ namespace: 'opencode-free-models' })
        if (bound && typeof bound.set === 'function') {
          bound.set('authRequired', authRequired)
          bound.set('authorized', authorized)
        }
      }
    } catch { /* ignore */ }
  }

  // 授权桥：把授权状态推给 node host（本机 HTTP，与参考插件 rotation proxy 同源）。
  // host 监听 127.0.0.1:<PORT>/ozf-auth；失败重试若干次以覆盖 host 尚未起好的竞态。
  const AUTH_BRIDGE_PORT = 18766
  function pushAuthState(authorized) {
    let attempts = 0
    const tryPost = () => {
      try {
        fetch(`http://127.0.0.1:${AUTH_BRIDGE_PORT}/ozf-auth`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ authorized: !!authorized }),
        }).catch(() => {})
      } catch { /* ignore */ }
      if (++attempts < 6) setTimeout(tryPost, 800)
    }
    tryPost()
  }

  // 面板挂载（受授权门禁控制）
  let detachDrawer = null
  const mountPanel = () => {
    if (detachDrawer) return
    detachDrawer = installRightDrawer()
    if (state.backendUrl) { loadPage(1); loadArticles(1) }
    else { renderAll(); renderArticles() }
    updateAuthStatus()
    track('pageview', 'panel_open')
  }

  runAuthGate(mountPanel)

  ctx.effect(() => () => {
    seq++
    if (timer) clearTimeout(timer)
    if (silentVerifyTimer) clearInterval(silentVerifyTimer)
    if (detachDrawer) detachDrawer()
    closeArticleModal()
    toastWrap.remove()
  })
}


const __exports__ = { name: name, inject: inject, apply: apply };
if (module) { module.exports = __exports__; }
return __exports__;
  }
});
