// @generated by scripts/build.mjs — do not edit by hand.
// dsh-opencode-free-models · pure core helpers (source of truth).
//
// Side-effect free so it can be unit-tested directly under node:test. The
// client bundle (lib/client.cjs) is generated by scripts/build.mjs, which
// concatenates THIS file (exports stripped) with src/client/index.js inside a
// lazy-CJS factory. Keep this file free of browser globals.
//
// Adapted from the dsh-free-models-hub reference plugin (MIT) for OpenCode Zen
// free models, which authenticate with one shared literal key ("public")
// injected by the host — so there is no per-user key and no rotation proxy.

export const PLUGIN_ID = 'opencode-free-models'
export const LOG_PREFIX = '[opencode-free-models]'
export const SETTINGS_NS = 'llm-pi-ai'
export const SECTION_NS = 'opencode-free-models'

// All OpenCode Zen free providers share this single literal-key env var. The
// host half injects OPENCODE_ZEN_API_KEY="public" on load, so no user key is
// ever required or touched by this plugin.
export const PUBLIC_KEY_ENV = 'OPENCODE_ZEN_API_KEY'

export const DEFAULT_FOOTER_LINKS = Object.freeze([
  Object.freeze({ label: '技术笔记', url: 'http://blog.4wc.cn' }),
  Object.freeze({ label: '插件开发', url: 'https://blog.gd7.cn/' }),
  Object.freeze({ label: '联系站长', url: 'http://web.wuyiyun.cn/' }),
])

export const CONFIG_DEFAULTS = Object.freeze({
  backendUrl: 'https://free-api.gd7.cn/opencode',
  pageSize: 20,
  requestTimeoutMs: 10000,
  uiSlot: '', // empty = deterministic right-edge drawer with its own toggle
  providerIdPrefix: 'opencode',
  footerLinks: DEFAULT_FOOTER_LINKS,
  debug: false,
})

/** Coerce to an integer inside [min,max]; anything else falls back. */
export function clampInt(value, min, max, fallback) {
  const n = Math.floor(Number(value))
  if (!Number.isFinite(n)) return fallback
  return Math.min(max, Math.max(min, n))
}

/** Only http(s) absolute URLs count as safe targets for links or fetches.
 *  Returns the canonical serialized URL — what we validate is exactly what
 *  the caller will use (the WHATWG parser strips smuggled control chars). */
export function safeHttpUrl(value) {
  if (typeof value !== 'string') return ''
  const trimmed = value.trim()
  if (!trimmed || trimmed.length > 2048) return ''
  let parsed
  try {
    parsed = new URL(trimmed)
  } catch {
    return ''
  }
  if (parsed.protocol !== 'http:' && parsed.protocol !== 'https:') return ''
  return parsed.toString()
}

/** Stable, lowercase provider-id fragment derived from a model title. */
export function slugify(title, maxLen = 40) {
  const base = String(title ?? '')
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, maxLen)
    .replace(/-+$/g, '')
  return base || 'model'
}

export function providerId(prefix, title, rowId) {
  const safePrefix = typeof prefix === 'string' && /^[a-z][a-z0-9-]{0,20}$/.test(prefix) ? prefix : 'opencode'
  const slug = slugify(title)
  if (Number.isFinite(rowId) && rowId > 0) return `${safePrefix}-${slug}-${rowId}`
  return `${safePrefix}-${slug}`
}

/** Single shared literal-key env for every OpenCode Zen free provider. */
export function apiKeyEnvName(/* pid */) {
  return PUBLIC_KEY_ENV
}

/**
 * Normalize raw patch/user config into a safe, fully-defaulted object.
 * Returns { value, warnings: string[] }; invalid fields fall back loudly.
 */
export function normalizeConfig(raw) {
  const src = raw && typeof raw === 'object' ? raw : {}
  const warnings = []
  const out = {}

  const backendUrl = safeHttpUrl(src.backendUrl)
  if (backendUrl) {
    out.backendUrl = backendUrl.replace(/\/+$/, '')
  } else {
    if (typeof src.backendUrl === 'string' && src.backendUrl.trim() !== '') {
      warnings.push(`backendUrl ignored (must be an absolute http/https URL): ${String(src.backendUrl).slice(0, 120)}`)
    }
    out.backendUrl = ''
  }

  out.pageSize = clampInt(src.pageSize, 1, 50, CONFIG_DEFAULTS.pageSize)
  out.requestTimeoutMs = clampInt(src.requestTimeoutMs, 1000, 60000, CONFIG_DEFAULTS.requestTimeoutMs)

  if (typeof src.uiSlot === 'string' && src.uiSlot.trim().length <= 64) {
    out.uiSlot = src.uiSlot.trim()
  } else {
    out.uiSlot = CONFIG_DEFAULTS.uiSlot
    if (src.uiSlot != null) warnings.push('uiSlot reset to default (non-empty string <= 64 chars expected)')
  }

  if (typeof src.providerIdPrefix === 'string' && /^[a-z][a-z0-9-]{0,20}$/.test(src.providerIdPrefix)) {
    out.providerIdPrefix = src.providerIdPrefix
  } else {
    out.providerIdPrefix = CONFIG_DEFAULTS.providerIdPrefix
    if (src.providerIdPrefix != null) warnings.push('providerIdPrefix reset to "opencode" (lowercase letters/digits/dashes, starts with a letter)')
  }

  const links = []
  if (Array.isArray(src.footerLinks)) {
    for (const raw of src.footerLinks.slice(0, 6)) {
      const item = raw && typeof raw === 'object' ? raw : {}
      const label = typeof item.label === 'string' ? item.label.trim().slice(0, 24) : ''
      const url = safeHttpUrl(item.url)
      if (label && url) links.push({ label, url })
      else warnings.push(`footerLink dropped (need label + http/https url): ${JSON.stringify(item).slice(0, 80)}`)
    }
  }
  out.footerLinks = links.length > 0 ? links : [...DEFAULT_FOOTER_LINKS]

  out.debug = src.debug === true

  return { value: out, warnings }
}

/**
 * Pagination window: numbers and '…' markers.
 */
export function pageWindow(current, total, width = 7) {
  const tot = clampInt(total, 1, Number.MAX_SAFE_INTEGER, 1)
  const cur = Math.min(clampInt(current, 1, Number.MAX_SAFE_INTEGER, 1), tot)
  const w = Math.max(5, clampInt(width, 5, 15, 7))
  if (tot <= w) {
    const all = []
    for (let i = 1; i <= tot; i++) all.push(i)
    return all
  }
  const mid = w - 2
  let start = Math.max(2, cur - ((mid - 1) >> 1))
  let end = Math.min(tot - 1, start + mid - 1)
  if (end >= tot - 1) {
    end = tot - 1
    start = Math.max(2, end - mid + 1)
  }
  const pages = [1]
  if (start > 2) pages.push('…')
  for (let i = start; i <= end; i++) pages.push(i)
  if (end < tot - 1) pages.push('…')
  pages.push(tot)
  return pages
}

function yamlQuote(value) {
  return `"${String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`
}

/** Fallback YAML snippet shown when live settings writes are unavailable. */
export function toYamlSnippet({ pid, entry }) {
  const lines = [
    'llm-pi-ai:',
    '  providers:',
    `    ${pid}:`,
    `      api: ${entry.api}`,
    `      baseURL: ${yamlQuote(entry.baseURL)}`,
    '      compat:',
    `        supportsDeveloperRole: ${entry.compat.supportsDeveloperRole}`,
    `        maxTokensField: ${entry.compat.maxTokensField}`,
    '      models:',
  ]
  for (const m of entry.models) {
    lines.push(`        - id: ${yamlQuote(m.id)}`)
  }
  return lines.join('\n')
}

/**
 * Build one llm-pi-ai provider entry for an OpenCode Zen free model.
 *
 * OpenCode Zen free models are PUBLIC: the completion API returns 200 with no
 * Authorization header at all (and equivalently accepts `Bearer public`). So
 * the entry deliberately declares NO apiKeyEnv — if we declared one, pi-ai
 * would demand that credential from its credentials service and report
 * "no credential". Omitting apiKeyEnv lets pi-ai use its own environment
 * discovery, which performs a no-auth request that the public API accepts.
 */
export function buildProviderEntry({ prefix, title, apiBase, modelIds, rowId }) {
  const pid = providerId(prefix, title, rowId)
  const models = Array.isArray(modelIds) && modelIds.length > 0
    ? modelIds.filter((m) => typeof m === 'string' && m.trim() !== '').map((m) => ({ id: m.trim() }))
    : [{ id: String(modelIds || '') }]
  return {
    pid,
    entry: {
      api: 'openai-completions',
      baseURL: String(apiBase),
      compat: {
        supportsDeveloperRole: false,
        maxTokensField: 'max_tokens',
      },
      models,
    },
  }
}

/**
 * Validate + map the OpenCode Zen free-models payload into canonical items.
 * Drops malformed rows instead of throwing on single bad entries.
 * Canonical item: { id, title, apiBase, modelIds, keyUrl, badge, pinned, status, disabledReason }
 */
export function parseModelsResponse(payload, pageSize) {
  if (!payload || typeof payload !== 'object' || payload.ok !== true) {
    throw new TypeError('response is not a valid models payload')
  }
  const total = clampInt(payload.total, 0, Number.MAX_SAFE_INTEGER, 0)
  const totalPages = clampInt(payload.total_pages, 1, Number.MAX_SAFE_INTEGER, 1)
  const page = clampInt(payload.page, 1, totalPages, 1)
  const size = clampInt(payload.page_size, 1, 50, clampInt(pageSize, 1, 50, 10))
  const rawItems = Array.isArray(payload.items) ? payload.items : []
  const items = []
  for (const row of rawItems.slice(0, size)) {
    if (!row || typeof row !== 'object') continue
    const id = Number(row.id)
    const title = typeof row.title === 'string' ? row.title.trim().slice(0, 200) : ''
    const apiBase = safeHttpUrl(row.api_base_url)
    let modelIds = []
    if (Array.isArray(row.model_name)) {
      modelIds = row.model_name.filter((m) => typeof m === 'string' && m.trim() !== '').map((m) => m.trim().slice(0, 120))
    } else if (typeof row.model_name === 'string' && row.model_name.trim() !== '') {
      modelIds = [row.model_name.trim().slice(0, 120)]
    }
    const keyUrl = safeHttpUrl(row.key_apply_url)
    const badge = row.badge === 'hot' || row.badge === 'rec' ? row.badge : ''
    const pinned = row.pinned === 1 || row.pinned === true
    const status = row.status === 'disabled' ? 'disabled' : 'enabled'
    const disabledReason = typeof row.disabled_reason === 'string' ? row.disabled_reason.slice(0, 120) : ''
    const usable = row.usable === false ? false : true
    const availableFrom = typeof row.available_from === 'string' ? row.available_from.slice(0, 32) : ''
    const availableUntil = typeof row.available_until === 'string' ? row.available_until.slice(0, 32) : ''
    if (!Number.isFinite(id) || !title || !apiBase || modelIds.length === 0) continue
    items.push({ id, title, apiBase, modelIds, keyUrl, badge, pinned, status, disabledReason, usable, availableFrom, availableUntil })
  }
  const globalEnabled = payload.opencode_enabled === false ? false : true
  return { total, totalPages, page, pageSize: size, items, globalEnabled }
}
