// @generated by scripts/build.mjs — do not edit by hand.
// dsh-opencode-free-models · Host half (Node side, source).
//
// Deliberately thin and defensive: every host-provided API is feature
// detected so version drift in the developer preview cannot fail the fiber.
// The browser half does the heavy lifting (panel UI, pagination, provider
// writes through settingsScope); this half normalizes config, injects the
// shared literal key env (OPENCODE_ZEN_API_KEY="public") so inserted
// providers need no user key, and optionally registers a settings section so
// the client can read resolved composition values.
//
// Adapted from dsh-free-models-hub (MIT). The local multi-key rotation proxy
// is intentionally omitted: OpenCode Zen free models use one shared literal
// key, so there is nothing to rotate.

import {
  CONFIG_DEFAULTS,
  LOG_PREFIX,
  SECTION_NS,
  normalizeConfig,
  PUBLIC_KEY_ENV,
} from './core.js'
import http from 'node:http'
import { PROVIDER, installOpenCodeFreeProvider } from './provider.js'

export const name = 'opencode-free-models'

// IMPORTANT: DSH's loader attaches services named here onto ctx before calling
// apply(ctx). Without this, ctx.llm is undefined and the opencode-free adapter
// never registers (no models in the picker). Same mechanism as dsh-opencode-zen.
export const inject = ['llm']

// ---- Discover DSH_HOME from the plugin's own install path ----
//   <DSH_HOME>/profiles/web/node_modules/<pkg>/lib/index.js  →  go up 6 dirs
let dshHome = ''
try {
  const { fileURLToPath } = await import('node:url')
  const { join } = await import('node:path')
  const here = fileURLToPath(import.meta.url)
  dshHome = join(here, '..', '..', '..', '..', '..', '..')
} catch {
  dshHome = process.cwd()
}
console.log(LOG_PREFIX, `host loaded (module: ${import.meta.url}); DSH_HOME=${dshHome}`)

// Prevent uncaught exceptions from crashing the host process
process.on('uncaughtException', (err) => {
  console.warn(LOG_PREFIX, 'uncaught exception (suppressed):', err && err.message)
})
process.on('unhandledRejection', (err) => {
  console.warn(LOG_PREFIX, 'unhandled rejection (suppressed):', err && err.message)
})

function log(debug, ...args) {
  if (debug) console.log(LOG_PREFIX, ...args)
}
function warn(...args) {
  console.warn(LOG_PREFIX, ...args)
}

export function apply(ctx, config = {}) {
  const { value: cfg, warnings } = normalizeConfig(config)
  for (const message of warnings) warn('config:', message)
  log(cfg.debug, 'loaded with config:', cfg)

  // Inject the shared literal key for any legacy extended-provider paths that
  // read OPENCODE_ZEN_API_KEY. Honors an operator override if present.
  // (The opencode-free provider registered below uses "Bearer public" directly.)
  if (!process.env[PUBLIC_KEY_ENV]) {
    process.env[PUBLIC_KEY_ENV] = 'public'
    log(cfg.debug, `injected ${PUBLIC_KEY_ENV}=public`)
  } else {
    log(cfg.debug, `${PUBLIC_KEY_ENV} already provided by environment; using it`)
  }

  // 免 key opencode-free provider。注册后模型出现在「输入框右下角模型选择器」。
  // 「暂停=全部失效」由两个开关共同决定（取与）：
  //   · localEnabled  —— 本插件 settings 区段的 enabled 开关（本机）。
  //   · remoteEnabled —— 远程后端（backendUrl/api/models）返回的 opencode_enabled
  //                      总开关。后台总开关(https://<host>/admin/opencode)关闭即 false。
  // 任一关闭 ⇒ provider 路由被 replace([]) 撤下并 emit llm/adapters-updated，
  // 模型从输入框选择器消失、任意发送被拒；全部开启即恢复。轮询读取远程总开关。
  let providerHandle = null
  let control = { enabled: () => true }
  let source = null
  let localEnabled = true
  let remoteEnabled = true
  // 授权门禁：authorized 由浏览器 client 通过本机 HTTP 桥（127.0.0.1，见
  // startAuthBridge）推送给 host。client 与 host 是不同进程、不共享 settingsScope，
  // 这是与参考插件 rotation-proxy 同源的可靠跨进程通道。
  // 默认 false（fail-closed）：后端要求授权时，未收到「已授权」信号即隐藏模型，
  // 与全局启用/暂停总开关关闭后模型不可见的行为一致；client 授权成功后推 true 即显示。
  let authorized = false
  // 后端授权总开关 auth_enabled：由 host 自身轮询 /api/license?act=status 获得，
  // 与 opencode_enabled 平行，不依赖面板是否打开。true ⇒ 后端要求先授权。
  let authRequired = false
  let remoteTimer = null
  let disposed = false
  let sectionDispose = null

  // 与全局启用/暂停总开关完全平行的因子：未授权 ⇒ provider 路由被 replace([])
  // 撤下（模型从输入框选择器消失、任意发送被拒），与 globalEnabled 暂停同机制。
  // authorized 由本机 HTTP 桥（startAuthBridge）写入，默认 false（见上）。
  const applyEnabled = () => {
    // 与全局总开关(opencode_enabled)完全平行：后端要求授权(authRequired) 且
    // 尚未授权(authorized !== true) ⇒ 停用免费模型（provider 路由撤下）。
    const authOk = !authRequired || authorized === true
    const enabled = localEnabled && remoteEnabled !== false && authOk
    control.enabled = () => enabled
    if (providerHandle && typeof providerHandle.replace === 'function') {
      try {
        // 关键：暂停/未授权时必须真正从注册表中移除 provider 路由并 emit
        // llm/adapters-updated，前端才会重新查询模型列表并把模型从输入框
        // 选择器移除。仅让 listModels() 返回 [] 不会刷新已缓存的列表。
        // replace([]) 是合法的（空路由仍保持注册），恢复时 replace([PROVIDER])。
        const next = enabled ? [PROVIDER] : []
        log(cfg.debug, `applyEnabled: local=${localEnabled} remote=${remoteEnabled} authRequired=${authRequired} authorized=${authorized} => routes ${JSON.stringify(next)}`)
        providerHandle.replace(next)
      } catch (error) {
        warn('route sync failed:', error && error.message)
      }
    }
  }

  try {
    control = { enabled: () => true }
    providerHandle = installOpenCodeFreeProvider(ctx, (msg) => console.log(LOG_PREFIX, msg), control)
    log(cfg.debug, 'provider registration finished')
  } catch (error) {
    warn('provider registration failed:', error && error.message)
  }

  // ---- 授权桥：浏览器 client 通过本机 HTTP POST 推送授权状态（127.0.0.1） ----
  // client 与 host 是不同进程、不共享 settingsScope，因此用本机 HTTP 监听作为
  // 可靠的跨进程通道（与参考插件的 rotation proxy 同源）。默认值 authorized=false
  // （fail-closed）：后端要求授权时未收到「已授权」即隐藏；client 授权成功推 true 即显示。
  const AUTH_BRIDGE_PORT = 18766
  let authBridgeServer = null
  const startAuthBridge = () => {
    try {
      const server = http.createServer((req, res) => {
        res.setHeader('Access-Control-Allow-Origin', '*')
        res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS')
        res.setHeader('Access-Control-Allow-Headers', 'Content-Type')
        if (req.method === 'OPTIONS') { res.writeHead(204); res.end(); return }
        if (req.method === 'POST' && req.url === '/ozf-auth') {
          let body = ''
          req.on('data', (chunk) => { body += chunk })
          req.on('end', () => {
            try {
              const data = JSON.parse(body || '{}')
              if (typeof data.authorized === 'boolean') {
                authorized = data.authorized
                log(cfg.debug, `auth bridge received authorized=${authorized}`)
                applyEnabled()
              }
              res.writeHead(200, { 'Content-Type': 'application/json' })
              res.end(JSON.stringify({ ok: true }))
            } catch {
              res.writeHead(400, { 'Content-Type': 'application/json' })
              res.end(JSON.stringify({ error: 'invalid json' }))
            }
          })
          return
        }
        res.writeHead(404, { 'Content-Type': 'application/json' })
        res.end(JSON.stringify({ error: 'not found' }))
      })
      server.on('error', (err) => warn('auth bridge listen error:', err && err.message))
      server.listen(AUTH_BRIDGE_PORT, '127.0.0.1', () => {
        console.log(LOG_PREFIX, `auth bridge listening on 127.0.0.1:${AUTH_BRIDGE_PORT}`)
      })
      authBridgeServer = server
    } catch (err) {
      warn('auth bridge failed to start:', err && err.message)
    }
  }
  startAuthBridge()

  // 读取远程后端总开关 opencode_enabled；true 保持启用，false 暂停（全部失效）。
  const pollRemoteSwitch = async (isFirst = false) => {
    if (disposed) return
    const base = (cfg.backendUrl || '').replace(/\/+$/, '')
    if (!base) {
      warn('no backendUrl; cannot read remote opencode_enabled — leaving enabled')
      remoteEnabled = true
      applyEnabled()
      return
    }
    let url
    try {
      const u = new URL(base)
      u.pathname = `${u.pathname.replace(/\/+$/, '')}/api/models`
      url = u.toString()
    } catch {
      warn('invalid backendUrl; leaving enabled')
      remoteEnabled = true
      applyEnabled()
      return
    }
    try {
      const controller = new AbortController()
      const timer = setTimeout(() => controller.abort(), cfg.requestTimeoutMs || 10000)
      try {
        const res = await fetch(url, { signal: controller.signal, headers: { Accept: 'application/json' } })
        if (!res.ok) throw new Error(`HTTP ${res.status}`)
        const payload = await res.json()
        const next = payload && payload.opencode_enabled !== false
        if (next !== remoteEnabled) log(cfg.debug, `remote opencode_enabled -> ${next}`)
        remoteEnabled = next
        rebuildModels(payload)
      } finally {
        clearTimeout(timer)
      }
    } catch (error) {
      // 读取失败保持现状（不因一次抖动误暂停/误启用）。
      log(cfg.debug, 'remote switch poll failed:', error && error.message)
    }
    applyEnabled()
    if (isFirst) {
      log(cfg.debug, `remote opencode_enabled(current) = ${remoteEnabled}`)
    }
  }

  // 读取后端「授权总开关」auth_enabled（与 opencode_enabled 平行，均由 host 自己轮询
  // 后端，不依赖面板是否打开）。仅当后端明确要求授权(auth_enabled=true) 且本地尚未授权
  // 时，才撤下免费模型；读取失败保持现状（不误杀、不误启用）。
  const pollLicenseSwitch = async (isFirst = false) => {
    if (disposed) return
    const base = (cfg.backendUrl || '').replace(/\/+$/, '')
    if (!base) { applyEnabled(); return }
    let url
    try {
      const u = new URL(base)
      u.pathname = `${u.pathname.replace(/\/+$/, '')}/api/license`
      u.search = '?act=status'
      url = u.toString()
    } catch { applyEnabled(); return }
    try {
      const controller = new AbortController()
      const timer = setTimeout(() => controller.abort(), cfg.requestTimeoutMs || 10000)
      try {
        const res = await fetch(url, { signal: controller.signal, headers: { Accept: 'application/json' } })
        if (!res.ok) throw new Error(`HTTP ${res.status}`)
        const payload = await res.json()
        const next = !!(payload && payload.auth_enabled)
        if (next !== authRequired) log(cfg.debug, `remote auth_enabled -> ${next}`)
        authRequired = next
      } finally {
        clearTimeout(timer)
      }
    } catch (error) {
      // 读取失败保持现状（不因一次抖动误暂停/误启用）。
      log(cfg.debug, 'license switch poll failed:', error && error.message)
    }
    applyEnabled()
    if (isFirst) {
      log(cfg.debug, `remote auth_enabled(current) = ${authRequired}`)
    }
  }

  // 用后端 /api/models 的最新有效模型重建 adapter 模型集（镜像后端，即镜像官方）。
  // 后端 enabled+usable（含可用时间窗）的 model_name 集合 = 当前应展示的官方免费模型：
  // 官方新增 → 后端有 → 自动进容器；官方弃用 → 后端没有 → 自动出容器。
  const rebuildModels = (payload) => {
    if (!providerHandle || typeof providerHandle.adapter?.setModels !== 'function') return
    const raw = Array.isArray(payload?.items) ? payload.items : []
    const seen = new Map()
    for (const row of raw) {
      if (!row || typeof row !== 'object') continue
      const enabled = row.status !== 'disabled'
      const usable = row.usable !== false
      if (!enabled || !usable) continue
      const ids = Array.isArray(row.model_name) ? row.model_name : (typeof row.model_name === 'string' && row.model_name ? [row.model_name] : [])
      const title = typeof row.title === 'string' && row.title.trim() ? row.title.trim() : ''
      for (const id of ids) {
        if (typeof id !== 'string' || !id.trim()) continue
        const key = id.trim()
        if (!seen.has(key)) {
          seen.set(key, { id: key, name: title || key, description: 'OpenCode Zen 免费档' })
        }
      }
    }
    const list = [...seen.values()]
    if (list.length === 0) return
    const removed = Array.isArray(providerHandle.adapter.models)
      ? providerHandle.adapter.models.filter((m) => !seen.has(m.id)).map((m) => m.id)
      : []
    providerHandle.adapter.setModels(list)
    log(cfg.debug, `backend models synced: ${list.length} active (${list.map((m) => m.id).join(', ')}); removed: ${removed.length ? removed.join(', ') : 'none'}`)
  }

  // 启动轮询：立即一次 + 每 30s 一次，随 fiber 清理。
  pollRemoteSwitch(true)
  pollLicenseSwitch(true)
  const POLL_INTERVAL_MS = 30000
  remoteTimer = setInterval(() => { void pollRemoteSwitch(); void pollLicenseSwitch() }, POLL_INTERVAL_MS)

  // Optional enhancement: expose our namespace on the settings page so the
  // resident (a) sees and flips the enabled/paused toggle and (b) reads resolved
  // values. Both imports are feature-detected; when missing we simply skip.
  Promise.all([
    import('@deepseek-ai/schemastery').catch(() => null),
    import('@deepseek-ai/dsh-settings').catch(() => null),
  ])
    .then(([schemastery, settings]) => {
      if (disposed) return
      if (!schemastery || !settings || typeof settings.installSettingsSection !== 'function') {
        log(cfg.debug, 'settings surface unavailable; skipping section registration')
        return
      }
      try {
        const Config = schemastery.object({
          enabled: schemastery.boolean().default(true),
          authorized: schemastery.boolean().default(true),
          backendUrl: schemastery.string().default(CONFIG_DEFAULTS.backendUrl),
          pageSize: schemastery.number().step(1).min(1).max(50).default(CONFIG_DEFAULTS.pageSize),
          requestTimeoutMs: schemastery.number().step(1).min(1000).max(60000).default(CONFIG_DEFAULTS.requestTimeoutMs),
          uiSlot: schemastery.string().default(CONFIG_DEFAULTS.uiSlot),
          providerIdPrefix: schemastery.string().default(CONFIG_DEFAULTS.providerIdPrefix),
          debug: schemastery.boolean().default(false),
        })
        const syncEnabled = () => {
          let enabled = true
          try {
            const v = source ? source() : cfg
            enabled = v ? v.enabled !== false : true
          } catch { /* keep current value */ }
          localEnabled = enabled
          log(cfg.debug, `local enabled toggle -> ${localEnabled}`)
          applyEnabled()
        }
        const disposer = settings.installSettingsSection(ctx, SECTION_NS, Config, cfg, {
          setSource: (get) => { source = get },
          onChange: () => syncEnabled(),
        })
        if (typeof disposer === 'function') sectionDispose = disposer
        syncEnabled()
        log(cfg.debug, `settings section "${SECTION_NS}" registered`)
      } catch (error) {
        log(cfg.debug, 'section registration failed:', error && error.message)
      }
    })
    .catch((error) => {
      if (!disposed) log(cfg.debug, 'optional settings setup skipped:', error && error.message)
    })

  ctx.effect(() => () => {
    disposed = true
    if (remoteTimer) {
      clearInterval(remoteTimer)
      remoteTimer = null
    }
    if (typeof providerHandle === 'function') {
      try {
        providerHandle()
      } catch { /* cleanup must never throw across unload */ }
      providerHandle = null
    }
    if (typeof sectionDispose === 'function') {
      try {
        sectionDispose()
      } catch { /* cleanup must never throw across unload */ }
    }
    if (authBridgeServer) {
      try { authBridgeServer.close() } catch { /* ignore */ }
      authBridgeServer = null
    }
  })

  log(cfg.debug, `host ready (backendUrl=${cfg.backendUrl || '(not configured)'}, pageSize=${cfg.pageSize})`)
}
